"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import axonclient.protos.common_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class CommandProviderOutbound(google.protobuf.message.Message):
    """An instruction from the components that provides the Command Handler towards AxonServer."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIBE_FIELD_NUMBER: builtins.int
    UNSUBSCRIBE_FIELD_NUMBER: builtins.int
    FLOW_CONTROL_FIELD_NUMBER: builtins.int
    COMMAND_RESPONSE_FIELD_NUMBER: builtins.int
    ACK_FIELD_NUMBER: builtins.int
    INSTRUCTION_ID_FIELD_NUMBER: builtins.int
    instruction_id: builtins.str
    """Instruction identifier. If this identifier is set, this instruction will be acknowledged via inbound stream"""
    @property
    def subscribe(self) -> Global___CommandSubscription:
        """Instruction to subscribe this component as handler of a specific type of command"""

    @property
    def unsubscribe(self) -> Global___CommandSubscription:
        """Instruction to unsubscribe this component as handler of a specific type of command"""

    @property
    def flow_control(self) -> axonclient.protos.common_pb2.FlowControl:
        """Instruction to increase the number of instructions AxonServer may send to this component"""

    @property
    def command_response(self) -> Global___CommandResponse:
        """Sends a result of Command processing"""

    @property
    def ack(self) -> axonclient.protos.common_pb2.InstructionAck:
        """Acknowledgement of previously sent instruction via inbound stream"""

    def __init__(
        self,
        *,
        subscribe: Global___CommandSubscription | None = ...,
        unsubscribe: Global___CommandSubscription | None = ...,
        flow_control: axonclient.protos.common_pb2.FlowControl | None = ...,
        command_response: Global___CommandResponse | None = ...,
        ack: axonclient.protos.common_pb2.InstructionAck | None = ...,
        instruction_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "command_response",
            b"command_response",
            "flow_control",
            b"flow_control",
            "request",
            b"request",
            "subscribe",
            b"subscribe",
            "unsubscribe",
            b"unsubscribe",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "command_response",
            b"command_response",
            "flow_control",
            b"flow_control",
            "instruction_id",
            b"instruction_id",
            "request",
            b"request",
            "subscribe",
            b"subscribe",
            "unsubscribe",
            b"unsubscribe",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["request", b"request"]
    ) -> (
        typing.Literal[
            "subscribe", "unsubscribe", "flow_control", "command_response", "ack"
        ]
        | None
    ): ...

Global___CommandProviderOutbound: typing_extensions.TypeAlias = CommandProviderOutbound

@typing.final
class CommandProviderInbound(google.protobuf.message.Message):
    """An instruction or confirmation from AxonServer towards the component that provides the Command Handler"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    INSTRUCTION_ID_FIELD_NUMBER: builtins.int
    instruction_id: builtins.str
    """Instruction identifier. If this identifier is set, this instruction will be acknowledged via outbound stream"""
    @property
    def ack(self) -> axonclient.protos.common_pb2.InstructionAck:
        """Acknowledgement of previously sent instruction via outbound stream"""

    @property
    def command(self) -> Global___Command:
        """A command for this component to process"""

    def __init__(
        self,
        *,
        ack: axonclient.protos.common_pb2.InstructionAck | None = ...,
        command: Global___Command | None = ...,
        instruction_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "ack", b"ack", "command", b"command", "request", b"request"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "command",
            b"command",
            "instruction_id",
            b"instruction_id",
            "request",
            b"request",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["request", b"request"]
    ) -> typing.Literal["ack", "command"] | None: ...

Global___CommandProviderInbound: typing_extensions.TypeAlias = CommandProviderInbound

@typing.final
class Command(google.protobuf.message.Message):
    """A message representing a Command that needs to be routed to a component capable of handling it"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> axonclient.protos.common_pb2.MetaDataValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: axonclient.protos.common_pb2.MetaDataValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    META_DATA_FIELD_NUMBER: builtins.int
    PROCESSING_INSTRUCTIONS_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The unique identifier of the Command Message"""
    name: builtins.str
    """The name of the command, used for routing it to a destination capable of handling it"""
    timestamp: builtins.int
    """The time at which the command was dispatched"""
    client_id: builtins.str
    """The unique identifier of the component dispatching this message"""
    component_name: builtins.str
    """The name/type of the component dispatching this message"""
    @property
    def payload(self) -> axonclient.protos.common_pb2.SerializedObject:
        """The payload of the Command, providing details on the instructions for the recipient"""

    @property
    def meta_data(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, axonclient.protos.common_pb2.MetaDataValue
    ]:
        """Meta Data entries of the Command Message, providing contextual information to the recipient"""

    @property
    def processing_instructions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        axonclient.protos.common_pb2.ProcessingInstruction
    ]:
        """Instructions for AxonServer when routing this Command Message"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        name: builtins.str = ...,
        timestamp: builtins.int = ...,
        payload: axonclient.protos.common_pb2.SerializedObject | None = ...,
        meta_data: (
            collections.abc.Mapping[
                builtins.str, axonclient.protos.common_pb2.MetaDataValue
            ]
            | None
        ) = ...,
        processing_instructions: (
            collections.abc.Iterable[axonclient.protos.common_pb2.ProcessingInstruction]
            | None
        ) = ...,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["payload", b"payload"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "message_identifier",
            b"message_identifier",
            "meta_data",
            b"meta_data",
            "name",
            b"name",
            "payload",
            b"payload",
            "processing_instructions",
            b"processing_instructions",
            "timestamp",
            b"timestamp",
        ],
    ) -> None: ...

Global___Command: typing_extensions.TypeAlias = Command

@typing.final
class CommandResponse(google.protobuf.message.Message):
    """Message representing the result of Command Handler execution"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> axonclient.protos.common_pb2.MetaDataValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: axonclient.protos.common_pb2.MetaDataValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    META_DATA_FIELD_NUMBER: builtins.int
    PROCESSING_INSTRUCTIONS_FIELD_NUMBER: builtins.int
    REQUEST_IDENTIFIER_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The unique identifier of the response message"""
    error_code: builtins.str
    """An error code describing the error, if any"""
    request_identifier: builtins.str
    """The unique identifier of the Command Message for which this is the response"""
    @property
    def error_message(self) -> axonclient.protos.common_pb2.ErrorMessage:
        """A detailed description of the error"""

    @property
    def payload(self) -> axonclient.protos.common_pb2.SerializedObject:
        """The payload to provide as a result to the dispatcher"""

    @property
    def meta_data(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, axonclient.protos.common_pb2.MetaDataValue
    ]:
        """Any meta data entries providing contextual information back to the dispatcher"""

    @property
    def processing_instructions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        axonclient.protos.common_pb2.ProcessingInstruction
    ]:
        """Instructions for AxonServer when routing this Command Response Message"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        error_code: builtins.str = ...,
        error_message: axonclient.protos.common_pb2.ErrorMessage | None = ...,
        payload: axonclient.protos.common_pb2.SerializedObject | None = ...,
        meta_data: (
            collections.abc.Mapping[
                builtins.str, axonclient.protos.common_pb2.MetaDataValue
            ]
            | None
        ) = ...,
        processing_instructions: (
            collections.abc.Iterable[axonclient.protos.common_pb2.ProcessingInstruction]
            | None
        ) = ...,
        request_identifier: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "error_message", b"error_message", "payload", b"payload"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "error_code",
            b"error_code",
            "error_message",
            b"error_message",
            "message_identifier",
            b"message_identifier",
            "meta_data",
            b"meta_data",
            "payload",
            b"payload",
            "processing_instructions",
            b"processing_instructions",
            "request_identifier",
            b"request_identifier",
        ],
    ) -> None: ...

Global___CommandResponse: typing_extensions.TypeAlias = CommandResponse

@typing.final
class CommandSubscription(google.protobuf.message.Message):
    """Message describing a component's capability of handling a command type"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    LOAD_FACTOR_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    """A unique identifier for this subscription. This identifier is returned in Acknowledgements to allow
    pipelining of subscription messages
    """
    command: builtins.str
    """The name of the command the component can handle"""
    component_name: builtins.str
    """The name/type of the component handling the command"""
    client_id: builtins.str
    """The unique identifier of the component instance subscribing"""
    load_factor: builtins.int
    """A number that represents the client's relative load capacity compared to other clients.
    This information is interpreted by Axon Server in relation to the other connected nodes' values.
    Used to balance the dispatching of commands. If set to 0, Axon Server consider 100 as default value.
    """
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        command: builtins.str = ...,
        component_name: builtins.str = ...,
        client_id: builtins.str = ...,
        load_factor: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "command",
            b"command",
            "component_name",
            b"component_name",
            "load_factor",
            b"load_factor",
            "message_id",
            b"message_id",
        ],
    ) -> None: ...

Global___CommandSubscription: typing_extensions.TypeAlias = CommandSubscription
