# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: axonclient/protos/command.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from axonclient.protos import common_pb2 as axonclient_dot_protos_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1f\x61xonclient/protos/command.proto\x12!io.axoniq.axonserver.grpc.command\x1a\x1e\x61xonclient/protos/common.proto"\xa2\x03\n\x17\x43ommandProviderOutbound\x12K\n\tsubscribe\x18\x01'
    b" \x01(\x0b\x32\x36.io.axoniq.axonserver.grpc.command.CommandSubscriptionH\x00\x12M\n\x0bunsubscribe\x18\x02"
    b" \x01(\x0b\x32\x36.io.axoniq.axonserver.grpc.command.CommandSubscriptionH\x00\x12>\n\x0c\x66low_control\x18\x03"
    b" \x01(\x0b\x32&.io.axoniq.axonserver.grpc.FlowControlH\x00\x12N\n\x10\x63ommand_response\x18\x04"
    b" \x01(\x0b\x32\x32.io.axoniq.axonserver.grpc.command.CommandResponseH\x00\x12\x38\n\x03\x61\x63k\x18\x05"
    b" \x01(\x0b\x32).io.axoniq.axonserver.grpc.InstructionAckH\x00\x12\x16\n\x0einstruction_id\x18\x06"
    b' \x01(\tB\t\n\x07request"\xb4\x01\n\x16\x43ommandProviderInbound\x12\x38\n\x03\x61\x63k\x18\x01'
    b" \x01(\x0b\x32).io.axoniq.axonserver.grpc.InstructionAckH\x00\x12=\n\x07\x63ommand\x18\x02"
    b" \x01(\x0b\x32*.io.axoniq.axonserver.grpc.command.CommandH\x00\x12\x16\n\x0einstruction_id\x18\x03"
    b' \x01(\tB\t\n\x07request"\xaa\x03\n\x07\x43ommand\x12\x1a\n\x12message_identifier\x18\x01'
    b" \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03"
    b" \x01(\x03\x12<\n\x07payload\x18\x04"
    b" \x01(\x0b\x32+.io.axoniq.axonserver.grpc.SerializedObject\x12K\n\tmeta_data\x18\x05"
    b" \x03(\x0b\x32\x38.io.axoniq.axonserver.grpc.command.Command.MetaDataEntry\x12Q\n\x17processing_instructions\x18\x06"
    b" \x03(\x0b\x32\x30.io.axoniq.axonserver.grpc.ProcessingInstruction\x12\x11\n\tclient_id\x18\x07"
    b" \x01(\t\x12\x16\n\x0e\x63omponent_name\x18\x08"
    b" \x01(\t\x1aY\n\rMetaDataEntry\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x37\n\x05value\x18\x02"
    b' \x01(\x0b\x32(.io.axoniq.axonserver.grpc.MetaDataValue:\x02\x38\x01"\xde\x03\n\x0f\x43ommandResponse\x12\x1a\n\x12message_identifier\x18\x01'
    b" \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12>\n\rerror_message\x18\x03"
    b" \x01(\x0b\x32'.io.axoniq.axonserver.grpc.ErrorMessage\x12<\n\x07payload\x18\x04"
    b" \x01(\x0b\x32+.io.axoniq.axonserver.grpc.SerializedObject\x12S\n\tmeta_data\x18\x05"
    b" \x03(\x0b\x32@.io.axoniq.axonserver.grpc.command.CommandResponse.MetaDataEntry\x12Q\n\x17processing_instructions\x18\x06"
    b" \x03(\x0b\x32\x30.io.axoniq.axonserver.grpc.ProcessingInstruction\x12\x1a\n\x12request_identifier\x18\x07"
    b" \x01(\t\x1aY\n\rMetaDataEntry\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x37\n\x05value\x18\x02"
    b' \x01(\x0b\x32(.io.axoniq.axonserver.grpc.MetaDataValue:\x02\x38\x01"z\n\x13\x43ommandSubscription\x12\x12\n\nmessage_id\x18\x01'
    b" \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02"
    b" \x01(\t\x12\x16\n\x0e\x63omponent_name\x18\x03"
    b" \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x13\n\x0bload_factor\x18\x05"
    b' \x01(\x05\x32\x8a\x02\n\x0e\x43ommandService\x12\x89\x01\n\nOpenStream\x12:.io.axoniq.axonserver.grpc.command.CommandProviderOutbound\x1a\x39.io.axoniq.axonserver.grpc.command.CommandProviderInbound"\x00(\x01\x30\x01\x12l\n\x08\x44ispatch\x12*.io.axoniq.axonserver.grpc.command.Command\x1a\x32.io.axoniq.axonserver.grpc.command.CommandResponse"\x00\x42\x02P\x01\x62\x06proto3'
)


_COMMANDPROVIDEROUTBOUND = DESCRIPTOR.message_types_by_name["CommandProviderOutbound"]
_COMMANDPROVIDERINBOUND = DESCRIPTOR.message_types_by_name["CommandProviderInbound"]
_COMMAND = DESCRIPTOR.message_types_by_name["Command"]
_COMMAND_METADATAENTRY = _COMMAND.nested_types_by_name["MetaDataEntry"]
_COMMANDRESPONSE = DESCRIPTOR.message_types_by_name["CommandResponse"]
_COMMANDRESPONSE_METADATAENTRY = _COMMANDRESPONSE.nested_types_by_name["MetaDataEntry"]
_COMMANDSUBSCRIPTION = DESCRIPTOR.message_types_by_name["CommandSubscription"]
CommandProviderOutbound = _reflection.GeneratedProtocolMessageType(
    "CommandProviderOutbound",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMANDPROVIDEROUTBOUND,
        "__module__": "axonclient.protos.command_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.CommandProviderOutbound)
    },
)
_sym_db.RegisterMessage(CommandProviderOutbound)

CommandProviderInbound = _reflection.GeneratedProtocolMessageType(
    "CommandProviderInbound",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMANDPROVIDERINBOUND,
        "__module__": "axonclient.protos.command_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.CommandProviderInbound)
    },
)
_sym_db.RegisterMessage(CommandProviderInbound)

Command = _reflection.GeneratedProtocolMessageType(
    "Command",
    (_message.Message,),
    {
        "MetaDataEntry": _reflection.GeneratedProtocolMessageType(
            "MetaDataEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _COMMAND_METADATAENTRY,
                "__module__": "axonclient.protos.command_pb2"
                # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.Command.MetaDataEntry)
            },
        ),
        "DESCRIPTOR": _COMMAND,
        "__module__": "axonclient.protos.command_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.Command)
    },
)
_sym_db.RegisterMessage(Command)
_sym_db.RegisterMessage(Command.MetaDataEntry)

CommandResponse = _reflection.GeneratedProtocolMessageType(
    "CommandResponse",
    (_message.Message,),
    {
        "MetaDataEntry": _reflection.GeneratedProtocolMessageType(
            "MetaDataEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _COMMANDRESPONSE_METADATAENTRY,
                "__module__": "axonclient.protos.command_pb2"
                # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.CommandResponse.MetaDataEntry)
            },
        ),
        "DESCRIPTOR": _COMMANDRESPONSE,
        "__module__": "axonclient.protos.command_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.CommandResponse)
    },
)
_sym_db.RegisterMessage(CommandResponse)
_sym_db.RegisterMessage(CommandResponse.MetaDataEntry)

CommandSubscription = _reflection.GeneratedProtocolMessageType(
    "CommandSubscription",
    (_message.Message,),
    {
        "DESCRIPTOR": _COMMANDSUBSCRIPTION,
        "__module__": "axonclient.protos.command_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.command.CommandSubscription)
    },
)
_sym_db.RegisterMessage(CommandSubscription)

_COMMANDSERVICE = DESCRIPTOR.services_by_name["CommandService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"P\001"
    _COMMAND_METADATAENTRY._options = None
    _COMMAND_METADATAENTRY._serialized_options = b"8\001"
    _COMMANDRESPONSE_METADATAENTRY._options = None
    _COMMANDRESPONSE_METADATAENTRY._serialized_options = b"8\001"
    _COMMANDPROVIDEROUTBOUND._serialized_start = 103
    _COMMANDPROVIDEROUTBOUND._serialized_end = 521
    _COMMANDPROVIDERINBOUND._serialized_start = 524
    _COMMANDPROVIDERINBOUND._serialized_end = 704
    _COMMAND._serialized_start = 707
    _COMMAND._serialized_end = 1133
    _COMMAND_METADATAENTRY._serialized_start = 1044
    _COMMAND_METADATAENTRY._serialized_end = 1133
    _COMMANDRESPONSE._serialized_start = 1136
    _COMMANDRESPONSE._serialized_end = 1614
    _COMMANDRESPONSE_METADATAENTRY._serialized_start = 1044
    _COMMANDRESPONSE_METADATAENTRY._serialized_end = 1133
    _COMMANDSUBSCRIPTION._serialized_start = 1616
    _COMMANDSUBSCRIPTION._serialized_end = 1738
    _COMMANDSERVICE._serialized_start = 1741
    _COMMANDSERVICE._serialized_end = 2007
# @@protoc_insertion_point(module_scope)
