# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: axonclient/protos/common.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)
from google.protobuf.internal import enum_type_wrapper

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1e\x61xonclient/protos/common.proto\x12\x19io.axoniq.axonserver.grpc\x1a\x19google/protobuf/any.proto"@\n\x10SerializedObject\x12\x0c\n\x04type\x18\x01'
    b" \x01(\t\x12\x10\n\x08revision\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03"
    b' \x01(\x0c"\xba\x01\n\rMetaDataValue\x12\x14\n\ntext_value\x18\x01'
    b" \x01(\tH\x00\x12\x16\n\x0cnumber_value\x18\x02"
    b" \x01(\x12H\x00\x12\x17\n\rboolean_value\x18\x03"
    b" \x01(\x08H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04"
    b" \x01(\x01H\x00\x12\x42\n\x0b\x62ytes_value\x18\x05"
    b' \x01(\x0b\x32+.io.axoniq.axonserver.grpc.SerializedObjectH\x00\x42\x06\n\x04\x64\x61ta"\x87\x01\n\x15ProcessingInstruction\x12\x35\n\x03key\x18\x01'
    b" \x01(\x0e\x32(.io.axoniq.axonserver.grpc.ProcessingKey\x12\x37\n\x05value\x18\x02"
    b' \x01(\x0b\x32(.io.axoniq.axonserver.grpc.MetaDataValue"V\n\x0c\x45rrorMessage\x12\x0f\n\x07message\x18\x01'
    b" \x01(\t\x12\x10\n\x08location\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x03"
    b" \x03(\t\x12\x12\n\nerror_code\x18\x04"
    b' \x01(\t"7\n\x0b\x46lowControl\x12\x11\n\tclient_id\x18\x02'
    b" \x01(\t\x12\x0f\n\x07permits\x18\x03"
    b' \x01(\x03J\x04\x08\x01\x10\x02"q\n\x0eInstructionAck\x12\x16\n\x0einstruction_id\x18\x01'
    b" \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x36\n\x05\x65rror\x18\x03"
    b' \x01(\x0b\x32\'.io.axoniq.axonserver.grpc.ErrorMessage*`\n\rProcessingKey\x12\x0f\n\x0bROUTING_KEY\x10\x00\x12\x0c\n\x08PRIORITY\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x11\n\rNR_OF_RESULTS\x10\x03"\x04\x08\x04\x10\x04"\x04\x08\x05\x10\x05"\x04\x08\x06\x10\x06\x42\x02P\x01\x62\x06proto3'
)

_PROCESSINGKEY = DESCRIPTOR.enum_types_by_name["ProcessingKey"]
ProcessingKey = enum_type_wrapper.EnumTypeWrapper(_PROCESSINGKEY)
ROUTING_KEY = 0
PRIORITY = 1
TIMEOUT = 2
NR_OF_RESULTS = 3


_SERIALIZEDOBJECT = DESCRIPTOR.message_types_by_name["SerializedObject"]
_METADATAVALUE = DESCRIPTOR.message_types_by_name["MetaDataValue"]
_PROCESSINGINSTRUCTION = DESCRIPTOR.message_types_by_name["ProcessingInstruction"]
_ERRORMESSAGE = DESCRIPTOR.message_types_by_name["ErrorMessage"]
_FLOWCONTROL = DESCRIPTOR.message_types_by_name["FlowControl"]
_INSTRUCTIONACK = DESCRIPTOR.message_types_by_name["InstructionAck"]
SerializedObject = _reflection.GeneratedProtocolMessageType(
    "SerializedObject",
    (_message.Message,),
    {
        "DESCRIPTOR": _SERIALIZEDOBJECT,
        "__module__": "axonclient.protos.common_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.SerializedObject)
    },
)
_sym_db.RegisterMessage(SerializedObject)

MetaDataValue = _reflection.GeneratedProtocolMessageType(
    "MetaDataValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _METADATAVALUE,
        "__module__": "axonclient.protos.common_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.MetaDataValue)
    },
)
_sym_db.RegisterMessage(MetaDataValue)

ProcessingInstruction = _reflection.GeneratedProtocolMessageType(
    "ProcessingInstruction",
    (_message.Message,),
    {
        "DESCRIPTOR": _PROCESSINGINSTRUCTION,
        "__module__": "axonclient.protos.common_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.ProcessingInstruction)
    },
)
_sym_db.RegisterMessage(ProcessingInstruction)

ErrorMessage = _reflection.GeneratedProtocolMessageType(
    "ErrorMessage",
    (_message.Message,),
    {
        "DESCRIPTOR": _ERRORMESSAGE,
        "__module__": "axonclient.protos.common_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.ErrorMessage)
    },
)
_sym_db.RegisterMessage(ErrorMessage)

FlowControl = _reflection.GeneratedProtocolMessageType(
    "FlowControl",
    (_message.Message,),
    {
        "DESCRIPTOR": _FLOWCONTROL,
        "__module__": "axonclient.protos.common_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.FlowControl)
    },
)
_sym_db.RegisterMessage(FlowControl)

InstructionAck = _reflection.GeneratedProtocolMessageType(
    "InstructionAck",
    (_message.Message,),
    {
        "DESCRIPTOR": _INSTRUCTIONACK,
        "__module__": "axonclient.protos.common_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.InstructionAck)
    },
)
_sym_db.RegisterMessage(InstructionAck)

if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"P\001"
    _PROCESSINGKEY._serialized_start = 741
    _PROCESSINGKEY._serialized_end = 837
    _SERIALIZEDOBJECT._serialized_start = 88
    _SERIALIZEDOBJECT._serialized_end = 152
    _METADATAVALUE._serialized_start = 155
    _METADATAVALUE._serialized_end = 341
    _PROCESSINGINSTRUCTION._serialized_start = 344
    _PROCESSINGINSTRUCTION._serialized_end = 479
    _ERRORMESSAGE._serialized_start = 481
    _ERRORMESSAGE._serialized_end = 567
    _FLOWCONTROL._serialized_start = 569
    _FLOWCONTROL._serialized_end = 624
    _INSTRUCTIONACK._serialized_start = 626
    _INSTRUCTIONACK._serialized_end = 739
# @@protoc_insertion_point(module_scope)
