"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import axonclient.protos.common_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PlatformInboundInstruction(google.protobuf.message.Message):
    """An instruction from Application Node to the AxonServer platform"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REGISTER_FIELD_NUMBER: builtins.int
    EVENT_PROCESSOR_INFO_FIELD_NUMBER: builtins.int
    HEARTBEAT_FIELD_NUMBER: builtins.int
    ACK_FIELD_NUMBER: builtins.int
    INSTRUCTION_ID_FIELD_NUMBER: builtins.int
    instruction_id: builtins.str
    """Instruction identifier. If this identifier is set, this instruction will be acknowledged via outbound stream"""
    @property
    def register(self) -> Global___ClientIdentification:
        """Information about the client being connected.
        This information is used by AxonServer to monitor the topology of connected applications.
        """

    @property
    def event_processor_info(self) -> Global___EventProcessorInfo:
        """Information about Tracking Processors defined in the application.
        This information is used by AxonServer to monitor the progress of Tracking Processors across instances.
        """

    @property
    def heartbeat(self) -> Global___Heartbeat:
        """This heartbeat is used by AxonServer in order to check if the connection is still alive"""

    @property
    def ack(self) -> axonclient.protos.common_pb2.InstructionAck:
        """Acknowledgement of previously sent instruction via outbound stream"""

    def __init__(
        self,
        *,
        register: Global___ClientIdentification | None = ...,
        event_processor_info: Global___EventProcessorInfo | None = ...,
        heartbeat: Global___Heartbeat | None = ...,
        ack: axonclient.protos.common_pb2.InstructionAck | None = ...,
        instruction_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "event_processor_info",
            b"event_processor_info",
            "heartbeat",
            b"heartbeat",
            "register",
            b"register",
            "request",
            b"request",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "event_processor_info",
            b"event_processor_info",
            "heartbeat",
            b"heartbeat",
            "instruction_id",
            b"instruction_id",
            "register",
            b"register",
            "request",
            b"request",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["request", b"request"]
    ) -> (
        typing.Literal["register", "event_processor_info", "heartbeat", "ack"] | None
    ): ...

Global___PlatformInboundInstruction: typing_extensions.TypeAlias = (
    PlatformInboundInstruction
)

@typing.final
class PlatformOutboundInstruction(google.protobuf.message.Message):
    """An instruction or information from the AxonServer Platform to the Application Node"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_NOTIFICATION_FIELD_NUMBER: builtins.int
    REQUEST_RECONNECT_FIELD_NUMBER: builtins.int
    PAUSE_EVENT_PROCESSOR_FIELD_NUMBER: builtins.int
    START_EVENT_PROCESSOR_FIELD_NUMBER: builtins.int
    RELEASE_SEGMENT_FIELD_NUMBER: builtins.int
    REQUEST_EVENT_PROCESSOR_INFO_FIELD_NUMBER: builtins.int
    SPLIT_EVENT_PROCESSOR_SEGMENT_FIELD_NUMBER: builtins.int
    MERGE_EVENT_PROCESSOR_SEGMENT_FIELD_NUMBER: builtins.int
    HEARTBEAT_FIELD_NUMBER: builtins.int
    ACK_FIELD_NUMBER: builtins.int
    INSTRUCTION_ID_FIELD_NUMBER: builtins.int
    instruction_id: builtins.str
    """Instruction identifier. If this identifier is set, this instruction will be acknowledged via inbound stream"""
    @property
    def node_notification(self) -> Global___NodeInfo:
        """Information provided by AxonServer which provides information about the AxonServer node the application is connected with"""

    @property
    def request_reconnect(self) -> Global___RequestReconnect:
        """A request from AxonServer to the Application to migrate its connection to another node.
        Clients SHOULD honor this request by closing their current connection, and using the GetPlatformServer RPC
        to request a new destination.
        """

    @property
    def pause_event_processor(self) -> Global___EventProcessorReference:
        """Instruction from AxonServer to Pause a Tracking Event Processor."""

    @property
    def start_event_processor(self) -> Global___EventProcessorReference:
        """Instruction from AxonServer to Start a Tracking Event Processor."""

    @property
    def release_segment(self) -> Global___EventProcessorSegmentReference:
        """Instruction from AxonServer to Release a specific segment in a Tracking Event Processor"""

    @property
    def request_event_processor_info(self) -> Global___EventProcessorReference:
        """A request from AxonServer for status information of a specific Tracking Event Processor"""

    @property
    def split_event_processor_segment(self) -> Global___EventProcessorSegmentReference:
        """Instruction to split a Segment in a Tracking Event Processor"""

    @property
    def merge_event_processor_segment(self) -> Global___EventProcessorSegmentReference:
        """Instruction to merge two Segments in a Tracking Event Processor"""

    @property
    def heartbeat(self) -> Global___Heartbeat:
        """This heartbeat is used by AxonFramework in order to check if the connection is still alive"""

    @property
    def ack(self) -> axonclient.protos.common_pb2.InstructionAck:
        """Acknowledgement of previously sent instruction via inbound stream"""

    def __init__(
        self,
        *,
        node_notification: Global___NodeInfo | None = ...,
        request_reconnect: Global___RequestReconnect | None = ...,
        pause_event_processor: Global___EventProcessorReference | None = ...,
        start_event_processor: Global___EventProcessorReference | None = ...,
        release_segment: Global___EventProcessorSegmentReference | None = ...,
        request_event_processor_info: Global___EventProcessorReference | None = ...,
        split_event_processor_segment: (
            Global___EventProcessorSegmentReference | None
        ) = ...,
        merge_event_processor_segment: (
            Global___EventProcessorSegmentReference | None
        ) = ...,
        heartbeat: Global___Heartbeat | None = ...,
        ack: axonclient.protos.common_pb2.InstructionAck | None = ...,
        instruction_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "heartbeat",
            b"heartbeat",
            "merge_event_processor_segment",
            b"merge_event_processor_segment",
            "node_notification",
            b"node_notification",
            "pause_event_processor",
            b"pause_event_processor",
            "release_segment",
            b"release_segment",
            "request",
            b"request",
            "request_event_processor_info",
            b"request_event_processor_info",
            "request_reconnect",
            b"request_reconnect",
            "split_event_processor_segment",
            b"split_event_processor_segment",
            "start_event_processor",
            b"start_event_processor",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "heartbeat",
            b"heartbeat",
            "instruction_id",
            b"instruction_id",
            "merge_event_processor_segment",
            b"merge_event_processor_segment",
            "node_notification",
            b"node_notification",
            "pause_event_processor",
            b"pause_event_processor",
            "release_segment",
            b"release_segment",
            "request",
            b"request",
            "request_event_processor_info",
            b"request_event_processor_info",
            "request_reconnect",
            b"request_reconnect",
            "split_event_processor_segment",
            b"split_event_processor_segment",
            "start_event_processor",
            b"start_event_processor",
        ],
    ) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["request", b"request"]) -> (
        typing.Literal[
            "node_notification",
            "request_reconnect",
            "pause_event_processor",
            "start_event_processor",
            "release_segment",
            "request_event_processor_info",
            "split_event_processor_segment",
            "merge_event_processor_segment",
            "heartbeat",
            "ack",
        ]
        | None
    ): ...

Global___PlatformOutboundInstruction: typing_extensions.TypeAlias = (
    PlatformOutboundInstruction
)

@typing.final
class RequestReconnect(google.protobuf.message.Message):
    """Message send when AxonServer requests the client to re-establish its connection with the Platform"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___RequestReconnect: typing_extensions.TypeAlias = RequestReconnect

@typing.final
class PlatformInfo(google.protobuf.message.Message):
    """Message containing connection information of the node to Connect with"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRIMARY_FIELD_NUMBER: builtins.int
    SAME_CONNECTION_FIELD_NUMBER: builtins.int
    same_connection: builtins.bool
    """Flag indicating that the connection may be reused to connect. When true, the client _may_ reuse the connection
    established for the GetPlatformServer request for subsequent requests.
    """
    @property
    def primary(self) -> Global___NodeInfo:
        """The connection details of the node the client should connect with"""

    def __init__(
        self,
        *,
        primary: Global___NodeInfo | None = ...,
        same_connection: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["primary", b"primary"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "primary", b"primary", "same_connection", b"same_connection"
        ],
    ) -> None: ...

Global___PlatformInfo: typing_extensions.TypeAlias = PlatformInfo

@typing.final
class NodeInfo(google.protobuf.message.Message):
    """Message containing connection information for an AxonServer Node"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_NAME_FIELD_NUMBER: builtins.int
    GRPC_PORT_FIELD_NUMBER: builtins.int
    HTTP_PORT_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    NODE_NAME_FIELD_NUMBER: builtins.int
    host_name: builtins.str
    """The host name to use when connecting to this node"""
    grpc_port: builtins.int
    """The port number for gRPC connections"""
    http_port: builtins.int
    """The port number for HTTP connections"""
    version: builtins.int
    """The version identifier of the API"""
    node_name: builtins.str
    """The unique name of the node to connect with, for purpose of debugging"""
    def __init__(
        self,
        *,
        host_name: builtins.str = ...,
        grpc_port: builtins.int = ...,
        http_port: builtins.int = ...,
        version: builtins.int = ...,
        node_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "grpc_port",
            b"grpc_port",
            "host_name",
            b"host_name",
            "http_port",
            b"http_port",
            "node_name",
            b"node_name",
            "version",
            b"version",
        ],
    ) -> None: ...

Global___NodeInfo: typing_extensions.TypeAlias = NodeInfo

@typing.final
class ClientIdentification(google.protobuf.message.Message):
    """Message containing details about the Client Application"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TagsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    TAGS_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    client_id: builtins.str
    """A unique identifier for this client instance. Is used to distinguish different instances of the same component"""
    component_name: builtins.str
    """The name of the component. Several instances of the same component should share this name"""
    version: builtins.str
    """Axon framework version used by the client application instance"""
    @property
    def tags(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Any tags associated with the client, which may provide hints and preferences for setting up connections"""

    def __init__(
        self,
        *,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
        tags: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "tags",
            b"tags",
            "version",
            b"version",
        ],
    ) -> None: ...

Global___ClientIdentification: typing_extensions.TypeAlias = ClientIdentification

@typing.final
class EventProcessorInfo(google.protobuf.message.Message):
    """Message containing information about the status of a Tracking Event Processor"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SegmentStatus(google.protobuf.message.Message):
        """Message containing information about the status of a Segment of a Tracking Event Processor"""

        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SEGMENT_ID_FIELD_NUMBER: builtins.int
        CAUGHT_UP_FIELD_NUMBER: builtins.int
        REPLAYING_FIELD_NUMBER: builtins.int
        ONE_PART_OF_FIELD_NUMBER: builtins.int
        TOKEN_POSITION_FIELD_NUMBER: builtins.int
        ERROR_STATE_FIELD_NUMBER: builtins.int
        segment_id: builtins.int
        """The ID of the Segment for which the status is reported"""
        caught_up: builtins.bool
        """Indicates whether the Segment has "Caught Up" with the Head of the Event Stream"""
        replaying: builtins.bool
        """Indicates whether the Segment is "Replaying" historic events after a Reset."""
        one_part_of: builtins.int
        """The fraction this segment processes. A fraction of 2 means 1/2, 4 means 1/4, etc."""
        token_position: builtins.int
        """The approximate position of the token in the stream."""
        error_state: builtins.str
        """Information about the error state of the Segment, if applicable."""
        def __init__(
            self,
            *,
            segment_id: builtins.int = ...,
            caught_up: builtins.bool = ...,
            replaying: builtins.bool = ...,
            one_part_of: builtins.int = ...,
            token_position: builtins.int = ...,
            error_state: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self,
            field_name: typing.Literal[
                "caught_up",
                b"caught_up",
                "error_state",
                b"error_state",
                "one_part_of",
                b"one_part_of",
                "replaying",
                b"replaying",
                "segment_id",
                b"segment_id",
                "token_position",
                b"token_position",
            ],
        ) -> None: ...

    PROCESSOR_NAME_FIELD_NUMBER: builtins.int
    MODE_FIELD_NUMBER: builtins.int
    ACTIVE_THREADS_FIELD_NUMBER: builtins.int
    RUNNING_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    SEGMENT_STATUS_FIELD_NUMBER: builtins.int
    AVAILABLE_THREADS_FIELD_NUMBER: builtins.int
    processor_name: builtins.str
    """The logical name of this processor."""
    mode: builtins.str
    """The mode in which this processor is reading Events, for example: 'Tracking' or 'Subscribing'"""
    active_threads: builtins.int
    """The number of threads currently actively processing Events"""
    running: builtins.bool
    """Flag indicating whether the processor is running"""
    error: builtins.bool
    """Flag indicating whether the processor, when stopped, did so because of an irrecoverable Error"""
    available_threads: builtins.int
    """The number of threads the processor has available to assign to Segments.
    Will report 0 if all threads are assigned a Segment.
    """
    @property
    def segment_status(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___EventProcessorInfo.SegmentStatus
    ]:
        """Status details of each of the Segments for which Events are being processed. This is only provided by Tracking
        Event Processors.
        """

    def __init__(
        self,
        *,
        processor_name: builtins.str = ...,
        mode: builtins.str = ...,
        active_threads: builtins.int = ...,
        running: builtins.bool = ...,
        error: builtins.bool = ...,
        segment_status: (
            collections.abc.Iterable[Global___EventProcessorInfo.SegmentStatus] | None
        ) = ...,
        available_threads: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "active_threads",
            b"active_threads",
            "available_threads",
            b"available_threads",
            "error",
            b"error",
            "mode",
            b"mode",
            "processor_name",
            b"processor_name",
            "running",
            b"running",
            "segment_status",
            b"segment_status",
        ],
    ) -> None: ...

Global___EventProcessorInfo: typing_extensions.TypeAlias = EventProcessorInfo

@typing.final
class EventProcessorReference(google.protobuf.message.Message):
    """Message providing reference to an Event Processor"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROCESSOR_NAME_FIELD_NUMBER: builtins.int
    processor_name: builtins.str
    """The name of the Event Processor"""
    def __init__(
        self,
        *,
        processor_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["processor_name", b"processor_name"]
    ) -> None: ...

Global___EventProcessorReference: typing_extensions.TypeAlias = EventProcessorReference

@typing.final
class EventProcessorSegmentReference(google.protobuf.message.Message):
    """Message providing reference to a Segment of an Event Processor"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROCESSOR_NAME_FIELD_NUMBER: builtins.int
    SEGMENT_IDENTIFIER_FIELD_NUMBER: builtins.int
    processor_name: builtins.str
    """The name of the Event Processor"""
    segment_identifier: builtins.int
    """The identifier of the Segment"""
    def __init__(
        self,
        *,
        processor_name: builtins.str = ...,
        segment_identifier: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "processor_name",
            b"processor_name",
            "segment_identifier",
            b"segment_identifier",
        ],
    ) -> None: ...

Global___EventProcessorSegmentReference: typing_extensions.TypeAlias = (
    EventProcessorSegmentReference
)

@typing.final
class Heartbeat(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___Heartbeat: typing_extensions.TypeAlias = Heartbeat
