# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import warnings

import grpc

from axonclient.protos import (
    common_pb2 as axonclient_dot_protos_dot_common__pb2,
    dcb_pb2 as axonclient_dot_protos_dot_dcb__pb2,
)

GRPC_GENERATED_VERSION = "1.76.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in axonclient/protos/dcb_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class DcbEventStoreStub(object):
    """Service providing Event Store RPCs supporting DCB."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Append = channel.stream_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/Append",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.AppendEventsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.AppendEventsResponse.FromString,
            _registered_method=True,
        )
        self.Source = channel.unary_stream(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/Source",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.SourceEventsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.SourceEventsResponse.FromString,
            _registered_method=True,
        )
        self.Stream = channel.unary_stream(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/Stream",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.StreamEventsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.StreamEventsResponse.FromString,
            _registered_method=True,
        )
        self.GetHead = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetHead",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.GetHeadRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetHeadResponse.FromString,
            _registered_method=True,
        )
        self.GetTail = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetTail",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.GetTailRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetTailResponse.FromString,
            _registered_method=True,
        )
        self.GetSequenceAt = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetSequenceAt",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.GetSequenceAtRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetSequenceAtResponse.FromString,
            _registered_method=True,
        )
        self.AddTags = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/AddTags",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.AddTagsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.AddTagsResponse.FromString,
            _registered_method=True,
        )
        self.RemoveTags = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/RemoveTags",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.RemoveTagsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.RemoveTagsResponse.FromString,
            _registered_method=True,
        )
        self.GetTags = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetTags",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.GetTagsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetTagsResponse.FromString,
            _registered_method=True,
        )


class DcbEventStoreServicer(object):
    """Service providing Event Store RPCs supporting DCB."""

    def Append(self, request_iterator, context):
        """Appends new events to the store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Source(self, request, context):
        """Provides a finite stream of events based on the passed SourceEventsRequest."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Stream(self, request, context):
        """Provides an infinite stream of events based on the passed StreamEventsRequest."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetHead(self, request, context):
        """Gets the current _head_ of the Event Store. The _head_ points to the sequence of the first event to be appended."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTail(self, request, context):
        """Gets the current _tail_ of the Event Store. The _tail_ points to the sequence of the first event stored."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetSequenceAt(self, request, context):
        """Returns the lowest sequence of an event with a timestamp equal to or higher than the given timestamp. The HEAD is
        returned if no events exist with a timestamp equal to or higher than the given timestamp.

        N.B. Axon Server does not assign timestamps to events. The timestamps used for fulfilling this RPC are timestamps
        provided by the client. It could happen that there are events after the returned sequence that have an earlier
        timestamp. Axon Server does not reject appends if timestamps of events are not monotonically increasing.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def AddTags(self, request, context):
        """Assigns tags to the event identified by its sequence."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RemoveTags(self, request, context):
        """Removes tags from the event identified by its sequence."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetTags(self, request, context):
        """Gets tags for the event identified by its sequence."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DcbEventStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Append": grpc.stream_unary_rpc_method_handler(
            servicer.Append,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.AppendEventsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.AppendEventsResponse.SerializeToString,
        ),
        "Source": grpc.unary_stream_rpc_method_handler(
            servicer.Source,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.SourceEventsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.SourceEventsResponse.SerializeToString,
        ),
        "Stream": grpc.unary_stream_rpc_method_handler(
            servicer.Stream,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.StreamEventsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.StreamEventsResponse.SerializeToString,
        ),
        "GetHead": grpc.unary_unary_rpc_method_handler(
            servicer.GetHead,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetHeadRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.GetHeadResponse.SerializeToString,
        ),
        "GetTail": grpc.unary_unary_rpc_method_handler(
            servicer.GetTail,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetTailRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.GetTailResponse.SerializeToString,
        ),
        "GetSequenceAt": grpc.unary_unary_rpc_method_handler(
            servicer.GetSequenceAt,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetSequenceAtRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.GetSequenceAtResponse.SerializeToString,
        ),
        "AddTags": grpc.unary_unary_rpc_method_handler(
            servicer.AddTags,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.AddTagsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.AddTagsResponse.SerializeToString,
        ),
        "RemoveTags": grpc.unary_unary_rpc_method_handler(
            servicer.RemoveTags,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.RemoveTagsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.RemoveTagsResponse.SerializeToString,
        ),
        "GetTags": grpc.unary_unary_rpc_method_handler(
            servicer.GetTags,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetTagsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.GetTagsResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "io.axoniq.axonserver.grpc.event.dcb.DcbEventStore", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "io.axoniq.axonserver.grpc.event.dcb.DcbEventStore", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DcbEventStore(object):
    """Service providing Event Store RPCs supporting DCB."""

    @staticmethod
    def Append(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/Append",
            axonclient_dot_protos_dot_dcb__pb2.AppendEventsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.AppendEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Source(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/Source",
            axonclient_dot_protos_dot_dcb__pb2.SourceEventsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.SourceEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Stream(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/Stream",
            axonclient_dot_protos_dot_dcb__pb2.StreamEventsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.StreamEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetHead(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetHead",
            axonclient_dot_protos_dot_dcb__pb2.GetHeadRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.GetHeadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTail(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetTail",
            axonclient_dot_protos_dot_dcb__pb2.GetTailRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.GetTailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetSequenceAt(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetSequenceAt",
            axonclient_dot_protos_dot_dcb__pb2.GetSequenceAtRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.GetSequenceAtResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def AddTags(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/AddTags",
            axonclient_dot_protos_dot_dcb__pb2.AddTagsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.AddTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RemoveTags(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/RemoveTags",
            axonclient_dot_protos_dot_dcb__pb2.RemoveTagsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.RemoveTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetTags(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventStore/GetTags",
            axonclient_dot_protos_dot_dcb__pb2.GetTagsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.GetTagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class DcbSnapshotStoreStub(object):
    """Service providing Snapshot Store RPCs."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/Add",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.AddSnapshotRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.AddSnapshotResponse.FromString,
            _registered_method=True,
        )
        self.Delete = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/Delete",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.DeleteSnapshotsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.DeleteSnapshotsResponse.FromString,
            _registered_method=True,
        )
        self.List = channel.unary_stream(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/List",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.ListSnapshotsRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.ListSnapshotsResponse.FromString,
            _registered_method=True,
        )
        self.GetLast = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/GetLast",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.GetLastSnapshotRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetLastSnapshotResponse.FromString,
            _registered_method=True,
        )


class DcbSnapshotStoreServicer(object):
    """Service providing Snapshot Store RPCs."""

    def Add(self, request, context):
        """Adds a snapshot to the snapshot store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Delete(self, request, context):
        """Deletes a snapshot from the snapshot store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def List(self, request, context):
        """Retrieves snapshots from the snapshot store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetLast(self, request, context):
        """Gets the latest snapshot based on the request from the snapshot store."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DcbSnapshotStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Add": grpc.unary_unary_rpc_method_handler(
            servicer.Add,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.AddSnapshotRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.AddSnapshotResponse.SerializeToString,
        ),
        "Delete": grpc.unary_unary_rpc_method_handler(
            servicer.Delete,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.DeleteSnapshotsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.DeleteSnapshotsResponse.SerializeToString,
        ),
        "List": grpc.unary_stream_rpc_method_handler(
            servicer.List,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.ListSnapshotsRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.ListSnapshotsResponse.SerializeToString,
        ),
        "GetLast": grpc.unary_unary_rpc_method_handler(
            servicer.GetLast,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.GetLastSnapshotRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.GetLastSnapshotResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DcbSnapshotStore(object):
    """Service providing Snapshot Store RPCs."""

    @staticmethod
    def Add(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/Add",
            axonclient_dot_protos_dot_dcb__pb2.AddSnapshotRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.AddSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Delete(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/Delete",
            axonclient_dot_protos_dot_dcb__pb2.DeleteSnapshotsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.DeleteSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def List(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/List",
            axonclient_dot_protos_dot_dcb__pb2.ListSnapshotsRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.ListSnapshotsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetLast(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbSnapshotStore/GetLast",
            axonclient_dot_protos_dot_dcb__pb2.GetLastSnapshotRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.GetLastSnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )


class DcbEventSchedulerStub(object):
    """Service to use AxonServer as a provider of an EventScheduler"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScheduleEvent = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler/ScheduleEvent",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.ScheduleEventRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.ScheduleToken.FromString,
            _registered_method=True,
        )
        self.RescheduleEvent = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler/RescheduleEvent",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.RescheduleEventRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_dcb__pb2.ScheduleToken.FromString,
            _registered_method=True,
        )
        self.CancelScheduledEvent = channel.unary_unary(
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler/CancelScheduledEvent",
            request_serializer=axonclient_dot_protos_dot_dcb__pb2.CancelScheduledEventRequest.SerializeToString,
            response_deserializer=axonclient_dot_protos_dot_common__pb2.InstructionAck.FromString,
            _registered_method=True,
        )


class DcbEventSchedulerServicer(object):
    """Service to use AxonServer as a provider of an EventScheduler"""

    def ScheduleEvent(self, request, context):
        """Schedule the given event for publication at the given time}. The returned ScheduleToken can be used to reschedule or cancel the planned publication."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def RescheduleEvent(self, request, context):
        """Reschedule a scheduled event and optionally replace it by a new event."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelScheduledEvent(self, request, context):
        """Cancel the publication of a scheduled event. If the events has already been published, this method does nothing."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DcbEventSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ScheduleEvent": grpc.unary_unary_rpc_method_handler(
            servicer.ScheduleEvent,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.ScheduleEventRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.ScheduleToken.SerializeToString,
        ),
        "RescheduleEvent": grpc.unary_unary_rpc_method_handler(
            servicer.RescheduleEvent,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.RescheduleEventRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_dcb__pb2.ScheduleToken.SerializeToString,
        ),
        "CancelScheduledEvent": grpc.unary_unary_rpc_method_handler(
            servicer.CancelScheduledEvent,
            request_deserializer=axonclient_dot_protos_dot_dcb__pb2.CancelScheduledEventRequest.FromString,
            response_serializer=axonclient_dot_protos_dot_common__pb2.InstructionAck.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class DcbEventScheduler(object):
    """Service to use AxonServer as a provider of an EventScheduler"""

    @staticmethod
    def ScheduleEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler/ScheduleEvent",
            axonclient_dot_protos_dot_dcb__pb2.ScheduleEventRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.ScheduleToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def RescheduleEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler/RescheduleEvent",
            axonclient_dot_protos_dot_dcb__pb2.RescheduleEventRequest.SerializeToString,
            axonclient_dot_protos_dot_dcb__pb2.ScheduleToken.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelScheduledEvent(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/io.axoniq.axonserver.grpc.event.dcb.DcbEventScheduler/CancelScheduledEvent",
            axonclient_dot_protos_dot_dcb__pb2.CancelScheduledEventRequest.SerializeToString,
            axonclient_dot_protos_dot_common__pb2.InstructionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
