"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ScheduleEventRequest(google.protobuf.message.Message):
    """Request message to schedule an event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANT_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    instant: builtins.int
    """timestamp when to publish the event"""
    @property
    def event(self) -> Global___Event:
        """the event to publish"""

    def __init__(
        self,
        *,
        instant: builtins.int = ...,
        event: Global___Event | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["event", b"event"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["event", b"event", "instant", b"instant"]
    ) -> None: ...

Global___ScheduleEventRequest: typing_extensions.TypeAlias = ScheduleEventRequest

@typing.final
class RescheduleEventRequest(google.protobuf.message.Message):
    """Request message to reschedule an event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    INSTANT_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    token: builtins.str
    """schedule token of the event to reschedule"""
    instant: builtins.int
    """timestamp when to publish the event"""
    @property
    def event(self) -> Global___Event:
        """optionally provide a new event to publish"""

    def __init__(
        self,
        *,
        token: builtins.str = ...,
        instant: builtins.int = ...,
        event: Global___Event | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["event", b"event"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "event", b"event", "instant", b"instant", "token", b"token"
        ],
    ) -> None: ...

Global___RescheduleEventRequest: typing_extensions.TypeAlias = RescheduleEventRequest

@typing.final
class CancelScheduledEventRequest(google.protobuf.message.Message):
    """Request message to cancel an event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    """token of scheduled event to cancel"""
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

Global___CancelScheduledEventRequest: typing_extensions.TypeAlias = (
    CancelScheduledEventRequest
)

@typing.final
class ScheduleToken(google.protobuf.message.Message):
    """Token to manage a scheduled event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.str
    """Field defining the token identifier"""
    def __init__(
        self,
        *,
        token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

Global___ScheduleToken: typing_extensions.TypeAlias = ScheduleToken

@typing.final
class Event(google.protobuf.message.Message):
    """The event message."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    IDENTIFIER_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    identifier: builtins.str
    """The unique identifier of the event."""
    timestamp: builtins.int
    """The timestamp of the event."""
    name: builtins.str
    """The name of the event."""
    version: builtins.str
    """The version of the event."""
    payload: builtins.bytes
    """The payload of the event."""
    @property
    def metadata(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """The metadata of the event."""

    def __init__(
        self,
        *,
        identifier: builtins.str = ...,
        timestamp: builtins.int = ...,
        name: builtins.str = ...,
        version: builtins.str = ...,
        payload: builtins.bytes = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "identifier",
            b"identifier",
            "metadata",
            b"metadata",
            "name",
            b"name",
            "payload",
            b"payload",
            "timestamp",
            b"timestamp",
            "version",
            b"version",
        ],
    ) -> None: ...

Global___Event: typing_extensions.TypeAlias = Event

@typing.final
class Tag(google.protobuf.message.Message):
    """The tag. Describes an event with more details. Usually using concepts from the Domain."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key of the tag."""
    value: builtins.bytes
    """The value of the tag."""
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        value: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["key", b"key", "value", b"value"]
    ) -> None: ...

Global___Tag: typing_extensions.TypeAlias = Tag

@typing.final
class TaggedEvent(google.protobuf.message.Message):
    """The event described in more details by a list of tags."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> Global___Event:
        """The event."""

    @property
    def tag(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Tag
    ]:
        """List of tags describing the given event in more details."""

    def __init__(
        self,
        *,
        event: Global___Event | None = ...,
        tag: collections.abc.Iterable[Global___Tag] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["event", b"event"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["event", b"event", "tag", b"tag"]
    ) -> None: ...

Global___TaggedEvent: typing_extensions.TypeAlias = TaggedEvent

@typing.final
class SequencedEvent(google.protobuf.message.Message):
    """The event retrieved from the event store with its corresponding sequence."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the event."""
    @property
    def event(self) -> Global___Event:
        """The event."""

    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
        event: Global___Event | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["event", b"event"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["event", b"event", "sequence", b"sequence"]
    ) -> None: ...

Global___SequencedEvent: typing_extensions.TypeAlias = SequencedEvent

@typing.final
class AppendEventsRequest(google.protobuf.message.Message):
    """The message representing the request to append events to the event store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONDITION_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    @property
    def condition(self) -> Global___ConsistencyCondition:
        """The condition used to check the validity of this request. If omitted, events will be appended unconditionally."""

    @property
    def event(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___TaggedEvent
    ]:
        """A list of tagged events to be appended to the event store if the condition is met.
        These events are considered as a transaction - they are either all appended or none of them are appended.
        The event store will index the events based on provided tags for future faster retrieval.
        """

    def __init__(
        self,
        *,
        condition: Global___ConsistencyCondition | None = ...,
        event: collections.abc.Iterable[Global___TaggedEvent] | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["condition", b"condition"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["condition", b"condition", "event", b"event"]
    ) -> None: ...

Global___AppendEventsRequest: typing_extensions.TypeAlias = AppendEventsRequest

@typing.final
class AppendEventsResponse(google.protobuf.message.Message):
    """The response of a successful append events request. If there was an issue with the append events request,
    the stream will complete with an error.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_OF_THE_FIRST_EVENT_FIELD_NUMBER: builtins.int
    TRANSACTION_SIZE_FIELD_NUMBER: builtins.int
    CONSISTENCY_MARKER_FIELD_NUMBER: builtins.int
    sequence_of_the_first_event: builtins.int
    """The sequence of the first event stored in the event store.
    Corresponding to the list of events (a transaction) passed in the AppendEventsRequest.
    """
    transaction_size: builtins.int
    """The number of events appended. Matches the number of events passed in the AppendEventsRequest."""
    consistency_marker: builtins.int
    """The consistency marker which may be used for a subsequent append events requests. Do note that during the time this
    consistency marker may get far behind the head of the event store which will increase the time needed for the append
    events request to be validated. If you don't plan to do subsequent append events requests in a "short" period of time,
    use the Source RPC to refresh the consistency marker.
    """
    def __init__(
        self,
        *,
        sequence_of_the_first_event: builtins.int = ...,
        transaction_size: builtins.int = ...,
        consistency_marker: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "consistency_marker",
            b"consistency_marker",
            "sequence_of_the_first_event",
            b"sequence_of_the_first_event",
            "transaction_size",
            b"transaction_size",
        ],
    ) -> None: ...

Global___AppendEventsResponse: typing_extensions.TypeAlias = AppendEventsResponse

@typing.final
class SourceEventsRequest(google.protobuf.message.Message):
    """The request to source events from the event store. It results in a finite stream of events completed by
    the event store. It may also be cancelled by the client. Only events matching the given criteria
    (a provided list of criterions) will be present in the stream. The stream is capped by the HEAD of the event store.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_SEQUENCE_FIELD_NUMBER: builtins.int
    CRITERION_FIELD_NUMBER: builtins.int
    from_sequence: builtins.int
    """An inclusive sequence of the first event to be included in the resulting stream."""
    @property
    def criterion(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Criterion
    ]:
        """The criteria consisting of the list of criterions. If at least one of these criterions is met,
        the criteria is met.
        """

    def __init__(
        self,
        *,
        from_sequence: builtins.int = ...,
        criterion: collections.abc.Iterable[Global___Criterion] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "criterion", b"criterion", "from_sequence", b"from_sequence"
        ],
    ) -> None: ...

Global___SourceEventsRequest: typing_extensions.TypeAlias = SourceEventsRequest

@typing.final
class SourceEventsResponse(google.protobuf.message.Message):
    """The response to the SourceEventsRequest. It consists either of an event (with its corresponding sequence) or a
    consistency marker. The consistency marker should be used in a following AppendEventsRequest related to the criteria used in the SourceEventsRequest this response originates from.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    CONSISTENCY_MARKER_FIELD_NUMBER: builtins.int
    consistency_marker: builtins.int
    """The consistency marker to be used for the following append related to the same criteria."""
    @property
    def event(self) -> Global___SequencedEvent:
        """The event matching the criteria with its corresponding sequence."""

    def __init__(
        self,
        *,
        event: Global___SequencedEvent | None = ...,
        consistency_marker: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "consistency_marker",
            b"consistency_marker",
            "event",
            b"event",
            "result",
            b"result",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "consistency_marker",
            b"consistency_marker",
            "event",
            b"event",
            "result",
            b"result",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["result", b"result"]
    ) -> typing.Literal["event", "consistency_marker"] | None: ...

Global___SourceEventsResponse: typing_extensions.TypeAlias = SourceEventsResponse

@typing.final
class ConsistencyCondition(google.protobuf.message.Message):
    """The condition for an AppendEventsRequest. Consists of the consistency marker and the criteria
    (a list of criterions).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONSISTENCY_MARKER_FIELD_NUMBER: builtins.int
    CRITERION_FIELD_NUMBER: builtins.int
    consistency_marker: builtins.int
    """The sequence used to start checking for the consistency of an append. If there are events with a sequence greater
    or equal than the consistency marker and those are matching the given criteria, the condition is not met and the transaction
    is rejected. Otherwise, it is accepted.
    """
    @property
    def criterion(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Criterion
    ]:
        """The criteria. Consists of a list of criterions. If a single criterion is met, the whole criteria is met."""

    def __init__(
        self,
        *,
        consistency_marker: builtins.int = ...,
        criterion: collections.abc.Iterable[Global___Criterion] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "consistency_marker", b"consistency_marker", "criterion", b"criterion"
        ],
    ) -> None: ...

Global___ConsistencyCondition: typing_extensions.TypeAlias = ConsistencyCondition

@typing.final
class Criterion(google.protobuf.message.Message):
    """The integral part of the criteria."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAGS_AND_NAMES_FIELD_NUMBER: builtins.int
    @property
    def tags_and_names(self) -> Global___TagsAndNamesCriterion:
        """The criterion based on event tags and event names."""

    def __init__(
        self,
        *,
        tags_and_names: Global___TagsAndNamesCriterion | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["tags_and_names", b"tags_and_names"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["tags_and_names", b"tags_and_names"]
    ) -> None: ...

Global___Criterion: typing_extensions.TypeAlias = Criterion

@typing.final
class TagsAndNamesCriterion(google.protobuf.message.Message):
    """The criterion based on event tags and event names. The event meets this criterion if ALL tags from this criterion
    are present in the tags of the event AND if the event name is present in one of the names of the this criterion.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    @property
    def name(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """A list of event names. The event meets this criterion if its name is in one of the names in this list."""

    @property
    def tag(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Tag
    ]:
        """A list of event tags. The event meets this criterion if it contains all the tags from this list. It meets the
        criterion if it contains more than provided list here, but it MUST contain all from the list.
        """

    def __init__(
        self,
        *,
        name: collections.abc.Iterable[builtins.str] | None = ...,
        tag: collections.abc.Iterable[Global___Tag] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["name", b"name", "tag", b"tag"]
    ) -> None: ...

Global___TagsAndNamesCriterion: typing_extensions.TypeAlias = TagsAndNamesCriterion

@typing.final
class StreamEventsRequest(google.protobuf.message.Message):
    """The request to provide an infinite stream of events from the event store. The client may cancel the stream at any
    time.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FROM_SEQUENCE_FIELD_NUMBER: builtins.int
    CRITERION_FIELD_NUMBER: builtins.int
    from_sequence: builtins.int
    """The inclusive sequence to start streaming from."""
    @property
    def criterion(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Criterion
    ]:
        """The criteria used to filter out events. Represented by a list of criterions. If at least one is met, the whole
        criteria is met.
        """

    def __init__(
        self,
        *,
        from_sequence: builtins.int = ...,
        criterion: collections.abc.Iterable[Global___Criterion] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "criterion", b"criterion", "from_sequence", b"from_sequence"
        ],
    ) -> None: ...

Global___StreamEventsRequest: typing_extensions.TypeAlias = StreamEventsRequest

@typing.final
class StreamEventsResponse(google.protobuf.message.Message):
    """The response to the StreamEventsRequest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> Global___SequencedEvent:
        """The event with its corresponding sequence."""

    def __init__(
        self,
        *,
        event: Global___SequencedEvent | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["event", b"event"]
    ) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["event", b"event"]) -> None: ...

Global___StreamEventsResponse: typing_extensions.TypeAlias = StreamEventsResponse

@typing.final
class GetHeadRequest(google.protobuf.message.Message):
    """The request to retrieve the current HEAD of the event store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetHeadRequest: typing_extensions.TypeAlias = GetHeadRequest

@typing.final
class GetHeadResponse(google.protobuf.message.Message):
    """The current HEAD of the event store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the current head. Points to the position of the first event to be appended. The HEAD of an empty
    event store is 0.
    """
    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["sequence", b"sequence"]
    ) -> None: ...

Global___GetHeadResponse: typing_extensions.TypeAlias = GetHeadResponse

@typing.final
class GetTailRequest(google.protobuf.message.Message):
    """The request to retrieve the current TAIL of the event store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetTailRequest: typing_extensions.TypeAlias = GetTailRequest

@typing.final
class GetTailResponse(google.protobuf.message.Message):
    """The current TAIL of the event store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the first event in the event store. 0 for an empty event store. 0 for a non-truncated event store.
    Non-zero for a truncated event store.
    """
    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["sequence", b"sequence"]
    ) -> None: ...

Global___GetTailResponse: typing_extensions.TypeAlias = GetTailResponse

@typing.final
class GetSequenceAtRequest(google.protobuf.message.Message):
    """The request to get the sequence of the event whose timestamp is the same as the timestamp provided in the request.
    If there are no events with the exact timestamp, then the sequence of the first one after the provided timestamp is
    returned. If the provided timestamp is greater that the sequence of the last event in the event store,
    the HEAD is returned.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: builtins.int
    timestamp: builtins.int
    """The timestamp."""
    def __init__(
        self,
        *,
        timestamp: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["timestamp", b"timestamp"]
    ) -> None: ...

Global___GetSequenceAtRequest: typing_extensions.TypeAlias = GetSequenceAtRequest

@typing.final
class GetSequenceAtResponse(google.protobuf.message.Message):
    """The sequence of the event approximately close to the provided timestamp."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the event."""
    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["sequence", b"sequence"]
    ) -> None: ...

Global___GetSequenceAtResponse: typing_extensions.TypeAlias = GetSequenceAtResponse

@typing.final
class AddTagsRequest(google.protobuf.message.Message):
    """The request to add tags to the event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the event whose tags list will be expanded with the tags from the request."""
    @property
    def tag(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Tag
    ]:
        """The tags to be added to the event. If the event already contains a tag from the same list
        (with the same key and the value) the new one will be ignored.
        """

    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
        tag: collections.abc.Iterable[Global___Tag] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["sequence", b"sequence", "tag", b"tag"]
    ) -> None: ...

Global___AddTagsRequest: typing_extensions.TypeAlias = AddTagsRequest

@typing.final
class AddTagsResponse(google.protobuf.message.Message):
    """The response indicating a successful addition of tags to the event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___AddTagsResponse: typing_extensions.TypeAlias = AddTagsResponse

@typing.final
class RemoveTagsRequest(google.protobuf.message.Message):
    """The request to remove tags from the event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    TAG_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the event whose tags should be removed."""
    @property
    def tag(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Tag
    ]:
        """Tags to be removed. If the event is not tagged with listed tags, they are skipped."""

    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
        tag: collections.abc.Iterable[Global___Tag] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["sequence", b"sequence", "tag", b"tag"]
    ) -> None: ...

Global___RemoveTagsRequest: typing_extensions.TypeAlias = RemoveTagsRequest

@typing.final
class RemoveTagsResponse(google.protobuf.message.Message):
    """The response indicating a successful removal of tags for the event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___RemoveTagsResponse: typing_extensions.TypeAlias = RemoveTagsResponse

@typing.final
class GetTagsRequest(google.protobuf.message.Message):
    """The request to retrieve tags of the event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SEQUENCE_FIELD_NUMBER: builtins.int
    sequence: builtins.int
    """The sequence of the event whose tags should be retrieved."""
    def __init__(
        self,
        *,
        sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["sequence", b"sequence"]
    ) -> None: ...

Global___GetTagsRequest: typing_extensions.TypeAlias = GetTagsRequest

@typing.final
class GetTagsResponse(google.protobuf.message.Message):
    """The response containing tags of an event."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TAG_FIELD_NUMBER: builtins.int
    @property
    def tag(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___Tag
    ]:
        """The tags associated to the event."""

    def __init__(
        self,
        *,
        tag: collections.abc.Iterable[Global___Tag] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["tag", b"tag"]) -> None: ...

Global___GetTagsResponse: typing_extensions.TypeAlias = GetTagsResponse

@typing.final
class Snapshot(google.protobuf.message.Message):
    """The snapshot."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetadataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    METADATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    """The name of the snapshot."""
    version: builtins.str
    """The version of the snapshot."""
    payload: builtins.bytes
    """The payload of the snapshot."""
    timestamp: builtins.int
    """The timestamp of the snapshot."""
    @property
    def metadata(
        self,
    ) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """The metadata of the snapshot."""

    def __init__(
        self,
        *,
        name: builtins.str = ...,
        version: builtins.str = ...,
        payload: builtins.bytes = ...,
        timestamp: builtins.int = ...,
        metadata: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "metadata",
            b"metadata",
            "name",
            b"name",
            "payload",
            b"payload",
            "timestamp",
            b"timestamp",
            "version",
            b"version",
        ],
    ) -> None: ...

Global___Snapshot: typing_extensions.TypeAlias = Snapshot

@typing.final
class AddSnapshotRequest(google.protobuf.message.Message):
    """The request to add the snapshot to the snapshot store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    PRUNE_FIELD_NUMBER: builtins.int
    SNAPSHOT_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key this snapshot is added to."""
    sequence: builtins.int
    """The sequence of the snapshot. Usually linked to the sequence of the event in the event store up to which
    the snapshot is taken.
    """
    prune: builtins.bool
    """If set to true, older snapshots for the same key are pruned."""
    @property
    def snapshot(self) -> Global___Snapshot:
        """The snapshot."""

    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        sequence: builtins.int = ...,
        prune: builtins.bool = ...,
        snapshot: Global___Snapshot | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["snapshot", b"snapshot"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "key",
            b"key",
            "prune",
            b"prune",
            "sequence",
            b"sequence",
            "snapshot",
            b"snapshot",
        ],
    ) -> None: ...

Global___AddSnapshotRequest: typing_extensions.TypeAlias = AddSnapshotRequest

@typing.final
class AddSnapshotResponse(google.protobuf.message.Message):
    """The response indicating the successful addition of the snapshot."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___AddSnapshotResponse: typing_extensions.TypeAlias = AddSnapshotResponse

@typing.final
class DeleteSnapshotsRequest(google.protobuf.message.Message):
    """
    The request to delete the snapshot from the snapshot store.
    Deletes from a sequence of `0` to the specified `to_sequence`
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    TO_SEQUENCE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key the snapshot is identified by."""
    to_sequence: builtins.int
    """The exclusive upper bound sequence of the snapshot to end the deletion."""
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        to_sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["key", b"key", "to_sequence", b"to_sequence"]
    ) -> None: ...

Global___DeleteSnapshotsRequest: typing_extensions.TypeAlias = DeleteSnapshotsRequest

@typing.final
class DeleteSnapshotsResponse(google.protobuf.message.Message):
    """The response indicating the successful deletion of the snapshot."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___DeleteSnapshotsResponse: typing_extensions.TypeAlias = DeleteSnapshotsResponse

@typing.final
class ListSnapshotsRequest(google.protobuf.message.Message):
    """The request to retrieve all snapshots from the snapshot store based on the key and sequence bounds."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    FROM_SEQUENCE_FIELD_NUMBER: builtins.int
    TO_SEQUENCE_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key of the snapshot."""
    from_sequence: builtins.int
    """The inclusive bottom bound sequence used to filter out snapshots."""
    to_sequence: builtins.int
    """The exclusive upper bound sequence used to filter out snapshots."""
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        from_sequence: builtins.int = ...,
        to_sequence: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "from_sequence",
            b"from_sequence",
            "key",
            b"key",
            "to_sequence",
            b"to_sequence",
        ],
    ) -> None: ...

Global___ListSnapshotsRequest: typing_extensions.TypeAlias = ListSnapshotsRequest

@typing.final
class ListSnapshotsResponse(google.protobuf.message.Message):
    """The response to the ListSnapshotRequest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    SNAPSHOT_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key of the snapshot."""
    sequence: builtins.int
    """The sequence of the snapshot."""
    @property
    def snapshot(self) -> Global___Snapshot:
        """The snapshot."""

    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        sequence: builtins.int = ...,
        snapshot: Global___Snapshot | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["snapshot", b"snapshot"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "key", b"key", "sequence", b"sequence", "snapshot", b"snapshot"
        ],
    ) -> None: ...

Global___ListSnapshotsResponse: typing_extensions.TypeAlias = ListSnapshotsResponse

@typing.final
class GetLastSnapshotRequest(google.protobuf.message.Message):
    """The request to retrieve the snapshot with the highest sequence from the snapshot store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key of the snapshot."""
    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["key", b"key"]) -> None: ...

Global___GetLastSnapshotRequest: typing_extensions.TypeAlias = GetLastSnapshotRequest

@typing.final
class GetLastSnapshotResponse(google.protobuf.message.Message):
    """The response to GetLatestSnapshotRequest."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    KEY_FIELD_NUMBER: builtins.int
    SEQUENCE_FIELD_NUMBER: builtins.int
    SNAPSHOT_FIELD_NUMBER: builtins.int
    key: builtins.bytes
    """The key of the snapshot."""
    sequence: builtins.int
    """The sequence of the snapshot."""
    @property
    def snapshot(self) -> Global___Snapshot:
        """The snapshot."""

    def __init__(
        self,
        *,
        key: builtins.bytes = ...,
        sequence: builtins.int = ...,
        snapshot: Global___Snapshot | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["snapshot", b"snapshot"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "key", b"key", "sequence", b"sequence", "snapshot", b"snapshot"
        ],
    ) -> None: ...

Global___GetLastSnapshotResponse: typing_extensions.TypeAlias = GetLastSnapshotResponse
