"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import axonclient.protos.common_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetFirstTokenRequest(google.protobuf.message.Message):
    """Request message to receive the first Token (Tail Token) of the Event Stream"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetFirstTokenRequest: typing_extensions.TypeAlias = GetFirstTokenRequest

@typing.final
class GetLastTokenRequest(google.protobuf.message.Message):
    """Request message to receive the last Token (Head Token) of the Event Stream"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___GetLastTokenRequest: typing_extensions.TypeAlias = GetLastTokenRequest

@typing.final
class GetTokenAtRequest(google.protobuf.message.Message):
    """Request message to receive the Token that starts streaming events from the given timestamp"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INSTANT_FIELD_NUMBER: builtins.int
    instant: builtins.int
    """Timestamp expressed as milliseconds since epoch"""
    def __init__(
        self,
        *,
        instant: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["instant", b"instant"]) -> None: ...

Global___GetTokenAtRequest: typing_extensions.TypeAlias = GetTokenAtRequest

@typing.final
class TrackingToken(google.protobuf.message.Message):
    """Message containing the information necessary to track the position of events in the Event Stream"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    token: builtins.int
    """The value of the Token"""
    def __init__(
        self,
        *,
        token: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["token", b"token"]) -> None: ...

Global___TrackingToken: typing_extensions.TypeAlias = TrackingToken

@typing.final
class EventWithToken(google.protobuf.message.Message):
    """Message wrapping an Event and a Tracking Token"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOKEN_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    token: builtins.int
    """The Token representing the position of this Event in the Stream"""
    @property
    def event(self) -> Global___Event:
        """The actual Event Message"""

    def __init__(
        self,
        *,
        token: builtins.int = ...,
        event: Global___Event | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["event", b"event"]
    ) -> builtins.bool: ...
    def ClearField(
        self, field_name: typing.Literal["event", b"event", "token", b"token"]
    ) -> None: ...

Global___EventWithToken: typing_extensions.TypeAlias = EventWithToken

@typing.final
class QueryEventsRequest(google.protobuf.message.Message):
    """Message providing the parameters for executing a Query against AxonServer."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUERY_FIELD_NUMBER: builtins.int
    NUMBER_OF_PERMITS_FIELD_NUMBER: builtins.int
    LIVE_EVENTS_FIELD_NUMBER: builtins.int
    query: builtins.str
    """The query to execute against the Event Stream"""
    number_of_permits: builtins.int
    """The number of results AxonServer may send before new permits need to be provided"""
    live_events: builtins.bool
    """Whether to keep the query running against incoming events once the Head of the Stream is reached"""
    def __init__(
        self,
        *,
        query: builtins.str = ...,
        number_of_permits: builtins.int = ...,
        live_events: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "live_events",
            b"live_events",
            "number_of_permits",
            b"number_of_permits",
            "query",
            b"query",
        ],
    ) -> None: ...

Global___QueryEventsRequest: typing_extensions.TypeAlias = QueryEventsRequest

@typing.final
class QueryEventsResponse(google.protobuf.message.Message):
    """A message describing a response to a Query request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLUMNS_FIELD_NUMBER: builtins.int
    ROW_FIELD_NUMBER: builtins.int
    FILES_COMPLETED_FIELD_NUMBER: builtins.int
    @property
    def columns(self) -> Global___ColumnsResponse:
        """Provided when the response contains the names of the columns the response contains. This message typically arrives first."""

    @property
    def row(self) -> Global___RowResponse:
        """Provided when the response message contains results of the Query"""

    @property
    def files_completed(self) -> Global___Confirmation:
        """Provided when all historic events have been included in the query results"""

    def __init__(
        self,
        *,
        columns: Global___ColumnsResponse | None = ...,
        row: Global___RowResponse | None = ...,
        files_completed: Global___Confirmation | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "columns",
            b"columns",
            "data",
            b"data",
            "files_completed",
            b"files_completed",
            "row",
            b"row",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "columns",
            b"columns",
            "data",
            b"data",
            "files_completed",
            b"files_completed",
            "row",
            b"row",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["data", b"data"]
    ) -> typing.Literal["columns", "row", "files_completed"] | None: ...

Global___QueryEventsResponse: typing_extensions.TypeAlias = QueryEventsResponse

@typing.final
class ColumnsResponse(google.protobuf.message.Message):
    """Message containing the names of the columns returned in a Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLUMN_FIELD_NUMBER: builtins.int
    @property
    def column(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """The names of the columns provided in the query"""

    def __init__(
        self,
        *,
        column: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["column", b"column"]) -> None: ...

Global___ColumnsResponse: typing_extensions.TypeAlias = ColumnsResponse

@typing.final
class RowResponse(google.protobuf.message.Message):
    """Message providing Query Result data"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ValuesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> Global___QueryValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: Global___QueryValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    ID_VALUES_FIELD_NUMBER: builtins.int
    SORT_VALUES_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    @property
    def id_values(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___QueryValue
    ]:
        """The values which, when combined, uniquely update this row. Any previously received values with the same identifiers should be replaced with this value"""

    @property
    def sort_values(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___QueryValue
    ]:
        """The sorting values to use when sorting this response compared to the others."""

    @property
    def values(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, Global___QueryValue
    ]:
        """The actual data values for each of the columns, as a column name -> value mapping"""

    def __init__(
        self,
        *,
        id_values: collections.abc.Iterable[Global___QueryValue] | None = ...,
        sort_values: collections.abc.Iterable[Global___QueryValue] | None = ...,
        values: collections.abc.Mapping[builtins.str, Global___QueryValue] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "id_values",
            b"id_values",
            "sort_values",
            b"sort_values",
            "values",
            b"values",
        ],
    ) -> None: ...

Global___RowResponse: typing_extensions.TypeAlias = RowResponse

@typing.final
class ReadHighestSequenceNrRequest(google.protobuf.message.Message):
    """Describes the combination of an Aggregate Identifier and first expected Sequence number when opening an Aggregate-specific Event Stream"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGGREGATE_ID_FIELD_NUMBER: builtins.int
    FROM_SEQUENCE_NR_FIELD_NUMBER: builtins.int
    aggregate_id: builtins.str
    """The Identifier of the Aggregate for which to load events"""
    from_sequence_nr: builtins.int
    """The Sequence Number of the first event expected"""
    def __init__(
        self,
        *,
        aggregate_id: builtins.str = ...,
        from_sequence_nr: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "aggregate_id", b"aggregate_id", "from_sequence_nr", b"from_sequence_nr"
        ],
    ) -> None: ...

Global___ReadHighestSequenceNrRequest: typing_extensions.TypeAlias = (
    ReadHighestSequenceNrRequest
)

@typing.final
class ReadHighestSequenceNrResponse(google.protobuf.message.Message):
    """The highest Sequence Number found for the provided request"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TO_SEQUENCE_NR_FIELD_NUMBER: builtins.int
    to_sequence_nr: builtins.int
    """The sequence number of the latest event"""
    def __init__(
        self,
        *,
        to_sequence_nr: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["to_sequence_nr", b"to_sequence_nr"]
    ) -> None: ...

Global___ReadHighestSequenceNrResponse: typing_extensions.TypeAlias = (
    ReadHighestSequenceNrResponse
)

@typing.final
class Confirmation(google.protobuf.message.Message):
    """A confirmation to a request from the client"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    """True when successful, otherwise false"""
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___Confirmation: typing_extensions.TypeAlias = Confirmation

@typing.final
class GetAggregateEventsRequest(google.protobuf.message.Message):
    """Request describing the desire to read events for a specific Aggregate"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGGREGATE_ID_FIELD_NUMBER: builtins.int
    INITIAL_SEQUENCE_FIELD_NUMBER: builtins.int
    ALLOW_SNAPSHOTS_FIELD_NUMBER: builtins.int
    aggregate_id: builtins.str
    """The identifier of the aggregate to read events for"""
    initial_sequence: builtins.int
    """The sequence number of the first event to receive"""
    allow_snapshots: builtins.bool
    """Whether a snapshot may be returned as first element in the stream"""
    def __init__(
        self,
        *,
        aggregate_id: builtins.str = ...,
        initial_sequence: builtins.int = ...,
        allow_snapshots: builtins.bool = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "aggregate_id",
            b"aggregate_id",
            "allow_snapshots",
            b"allow_snapshots",
            "initial_sequence",
            b"initial_sequence",
        ],
    ) -> None: ...

Global___GetAggregateEventsRequest: typing_extensions.TypeAlias = (
    GetAggregateEventsRequest
)

@typing.final
class GetAggregateSnapshotsRequest(google.protobuf.message.Message):
    """Request message to retrieve Snapshot Events for a specific Aggregate instance"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AGGREGATE_ID_FIELD_NUMBER: builtins.int
    INITIAL_SEQUENCE_FIELD_NUMBER: builtins.int
    MAX_SEQUENCE_FIELD_NUMBER: builtins.int
    MAX_RESULTS_FIELD_NUMBER: builtins.int
    aggregate_id: builtins.str
    """The identifier to fetch the snapshots for"""
    initial_sequence: builtins.int
    """The minimal sequence number of the snapshots to retrieve"""
    max_sequence: builtins.int
    """The maximum sequence number of the snapshots to retrieve"""
    max_results: builtins.int
    """The maximum number of results to stream"""
    def __init__(
        self,
        *,
        aggregate_id: builtins.str = ...,
        initial_sequence: builtins.int = ...,
        max_sequence: builtins.int = ...,
        max_results: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "aggregate_id",
            b"aggregate_id",
            "initial_sequence",
            b"initial_sequence",
            "max_results",
            b"max_results",
            "max_sequence",
            b"max_sequence",
        ],
    ) -> None: ...

Global___GetAggregateSnapshotsRequest: typing_extensions.TypeAlias = (
    GetAggregateSnapshotsRequest
)

@typing.final
class GetEventsRequest(google.protobuf.message.Message):
    """Request message to open an Event Stream from the Event Store."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRACKING_TOKEN_FIELD_NUMBER: builtins.int
    NUMBER_OF_PERMITS_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    PROCESSOR_FIELD_NUMBER: builtins.int
    BLACKLIST_FIELD_NUMBER: builtins.int
    tracking_token: builtins.int
    """The token to start streaming from"""
    number_of_permits: builtins.int
    """The number of messages the server may send before it needs to wait for more permits"""
    client_id: builtins.str
    """The unique identifier of this client instance. Used for monitoring."""
    component_name: builtins.str
    """The component name of this client instance. Used for monitoring."""
    processor: builtins.str
    """The name of the processor requesting this stream. Used for monitoring."""
    @property
    def blacklist(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        Global___PayloadDescription
    ]:
        """An enumeration of payload types that need to be blacklisted. The Server will stop sending messages of these
        types in order to reduce I/O. Note that the Server may occasionally send a blacklisted message to prevent
        time-outs and stale tokens on clients.
        """

    def __init__(
        self,
        *,
        tracking_token: builtins.int = ...,
        number_of_permits: builtins.int = ...,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
        processor: builtins.str = ...,
        blacklist: collections.abc.Iterable[Global___PayloadDescription] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "blacklist",
            b"blacklist",
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "number_of_permits",
            b"number_of_permits",
            "processor",
            b"processor",
            "tracking_token",
            b"tracking_token",
        ],
    ) -> None: ...

Global___GetEventsRequest: typing_extensions.TypeAlias = GetEventsRequest

@typing.final
class Event(google.protobuf.message.Message):
    """Message containing the information of an Event"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> axonclient.protos.common_pb2.MetaDataValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: axonclient.protos.common_pb2.MetaDataValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    AGGREGATE_IDENTIFIER_FIELD_NUMBER: builtins.int
    AGGREGATE_SEQUENCE_NUMBER_FIELD_NUMBER: builtins.int
    AGGREGATE_TYPE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    META_DATA_FIELD_NUMBER: builtins.int
    SNAPSHOT_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The unique identifier of this event"""
    aggregate_identifier: builtins.str
    """The identifier of the Aggregate instance that published this event, if any"""
    aggregate_sequence_number: builtins.int
    """The sequence number of the Event in the Aggregate instance that published it, if any"""
    aggregate_type: builtins.str
    """The Type of the Aggregate instance that published this Event, if any"""
    timestamp: builtins.int
    """The timestamp of the Event"""
    snapshot: builtins.bool
    """Flag indicating whether the Event is a snapshot Event"""
    @property
    def payload(self) -> axonclient.protos.common_pb2.SerializedObject:
        """The Payload of the Event"""

    @property
    def meta_data(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, axonclient.protos.common_pb2.MetaDataValue
    ]:
        """The Meta Data of the Event"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        aggregate_identifier: builtins.str = ...,
        aggregate_sequence_number: builtins.int = ...,
        aggregate_type: builtins.str = ...,
        timestamp: builtins.int = ...,
        payload: axonclient.protos.common_pb2.SerializedObject | None = ...,
        meta_data: (
            collections.abc.Mapping[
                builtins.str, axonclient.protos.common_pb2.MetaDataValue
            ]
            | None
        ) = ...,
        snapshot: builtins.bool = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["payload", b"payload"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "aggregate_identifier",
            b"aggregate_identifier",
            "aggregate_sequence_number",
            b"aggregate_sequence_number",
            "aggregate_type",
            b"aggregate_type",
            "message_identifier",
            b"message_identifier",
            "meta_data",
            b"meta_data",
            "payload",
            b"payload",
            "snapshot",
            b"snapshot",
            "timestamp",
            b"timestamp",
        ],
    ) -> None: ...

Global___Event: typing_extensions.TypeAlias = Event

@typing.final
class QueryValue(google.protobuf.message.Message):
    """Value used in Query Responses to represent a value in its original type"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TEXT_VALUE_FIELD_NUMBER: builtins.int
    NUMBER_VALUE_FIELD_NUMBER: builtins.int
    BOOLEAN_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    text_value: builtins.str
    """The text value"""
    number_value: builtins.int
    """The (64 bits) integer value"""
    boolean_value: builtins.bool
    """The boolean value"""
    double_value: builtins.float
    """The (64 bits) floating point value"""
    def __init__(
        self,
        *,
        text_value: builtins.str = ...,
        number_value: builtins.int = ...,
        boolean_value: builtins.bool = ...,
        double_value: builtins.float = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "boolean_value",
            b"boolean_value",
            "data",
            b"data",
            "double_value",
            b"double_value",
            "number_value",
            b"number_value",
            "text_value",
            b"text_value",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "boolean_value",
            b"boolean_value",
            "data",
            b"data",
            "double_value",
            b"double_value",
            "number_value",
            b"number_value",
            "text_value",
            b"text_value",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["data", b"data"]
    ) -> (
        typing.Literal["text_value", "number_value", "boolean_value", "double_value"]
        | None
    ): ...

Global___QueryValue: typing_extensions.TypeAlias = QueryValue

@typing.final
class PayloadDescription(google.protobuf.message.Message):
    """Description of a Payload Type"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    REVISION_FIELD_NUMBER: builtins.int
    type: builtins.str
    """The type identifier of the Payload"""
    revision: builtins.str
    """The revision of the Payload Type"""
    def __init__(
        self,
        *,
        type: builtins.str = ...,
        revision: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["revision", b"revision", "type", b"type"]
    ) -> None: ...

Global___PayloadDescription: typing_extensions.TypeAlias = PayloadDescription
