# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: axonclient/protos/event.proto
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
    descriptor_pool as _descriptor_pool,
    message as _message,
    reflection as _reflection,
    symbol_database as _symbol_database,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from axonclient.protos import common_pb2 as axonclient_dot_protos_dot_common__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1d\x61xonclient/protos/event.proto\x12\x1fio.axoniq.axonserver.grpc.event\x1a\x1e\x61xonclient/protos/common.proto"\x16\n\x14GetFirstTokenRequest"\x15\n\x13GetLastTokenRequest"$\n\x11GetTokenAtRequest\x12\x0f\n\x07instant\x18\x01'
    b' \x01(\x03"\x1e\n\rTrackingToken\x12\r\n\x05token\x18\x01'
    b' \x01(\x03"V\n\x0e\x45ventWithToken\x12\r\n\x05token\x18\x01'
    b" \x01(\x03\x12\x35\n\x05\x65vent\x18\x02"
    b' \x01(\x0b\x32&.io.axoniq.axonserver.grpc.event.Event"S\n\x12QueryEventsRequest\x12\r\n\x05query\x18\x01'
    b" \x01(\t\x12\x19\n\x11number_of_permits\x18\x02"
    b" \x01(\x03\x12\x13\n\x0blive_events\x18\x03"
    b' \x01(\x08"\xe9\x01\n\x13QueryEventsResponse\x12\x43\n\x07\x63olumns\x18\x01'
    b" \x01(\x0b\x32\x30.io.axoniq.axonserver.grpc.event.ColumnsResponseH\x00\x12;\n\x03row\x18\x02"
    b" \x01(\x0b\x32,.io.axoniq.axonserver.grpc.event.RowResponseH\x00\x12H\n\x0f\x66iles_completed\x18\x03"
    b' \x01(\x0b\x32-.io.axoniq.axonserver.grpc.event.ConfirmationH\x00\x42\x06\n\x04\x64\x61ta"!\n\x0f\x43olumnsResponse\x12\x0e\n\x06\x63olumn\x18\x01'
    b' \x03(\t"\xb5\x02\n\x0bRowResponse\x12>\n\tid_values\x18\x01'
    b" \x03(\x0b\x32+.io.axoniq.axonserver.grpc.event.QueryValue\x12@\n\x0bsort_values\x18\x02"
    b" \x03(\x0b\x32+.io.axoniq.axonserver.grpc.event.QueryValue\x12H\n\x06values\x18\x03"
    b" \x03(\x0b\x32\x38.io.axoniq.axonserver.grpc.event.RowResponse.ValuesEntry\x1aZ\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12:\n\x05value\x18\x02"
    b' \x01(\x0b\x32+.io.axoniq.axonserver.grpc.event.QueryValue:\x02\x38\x01"N\n\x1cReadHighestSequenceNrRequest\x12\x14\n\x0c\x61ggregate_id\x18\x01'
    b" \x01(\t\x12\x18\n\x10\x66rom_sequence_nr\x18\x03"
    b' \x01(\x03"7\n\x1dReadHighestSequenceNrResponse\x12\x16\n\x0eto_sequence_nr\x18\x01'
    b' \x01(\x03"\x1f\n\x0c\x43onfirmation\x12\x0f\n\x07success\x18\x01'
    b' \x01(\x08"d\n\x19GetAggregateEventsRequest\x12\x14\n\x0c\x61ggregate_id\x18\x01'
    b" \x01(\t\x12\x18\n\x10initial_sequence\x18\x02"
    b" \x01(\x03\x12\x17\n\x0f\x61llow_snapshots\x18\x03"
    b' \x01(\x08"y\n\x1cGetAggregateSnapshotsRequest\x12\x14\n\x0c\x61ggregate_id\x18\x01'
    b" \x01(\t\x12\x18\n\x10initial_sequence\x18\x02"
    b" \x01(\x03\x12\x14\n\x0cmax_sequence\x18\x03"
    b" \x01(\x03\x12\x13\n\x0bmax_results\x18\x04"
    b' \x01(\x05"\xcb\x01\n\x10GetEventsRequest\x12\x16\n\x0etracking_token\x18\x01'
    b" \x01(\x03\x12\x19\n\x11number_of_permits\x18\x02"
    b" \x01(\x03\x12\x11\n\tclient_id\x18\x03"
    b" \x01(\t\x12\x16\n\x0e\x63omponent_name\x18\x04"
    b" \x01(\t\x12\x11\n\tprocessor\x18\x05 \x01(\t\x12\x46\n\tblacklist\x18\x06"
    b' \x03(\x0b\x32\x33.io.axoniq.axonserver.grpc.event.PayloadDescription"\x83\x03\n\x05\x45vent\x12\x1a\n\x12message_identifier\x18\x01'
    b" \x01(\t\x12\x1c\n\x14\x61ggregate_identifier\x18\x02"
    b" \x01(\t\x12!\n\x19\x61ggregate_sequence_number\x18\x03"
    b" \x01(\x03\x12\x16\n\x0e\x61ggregate_type\x18\x04"
    b" \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12<\n\x07payload\x18\x06"
    b" \x01(\x0b\x32+.io.axoniq.axonserver.grpc.SerializedObject\x12G\n\tmeta_data\x18\x07"
    b" \x03(\x0b\x32\x34.io.axoniq.axonserver.grpc.event.Event.MetaDataEntry\x12\x10\n\x08snapshot\x18\x08"
    b" \x01(\x08\x1aY\n\rMetaDataEntry\x12\x0b\n\x03key\x18\x01"
    b" \x01(\t\x12\x37\n\x05value\x18\x02"
    b' \x01(\x0b\x32(.io.axoniq.axonserver.grpc.MetaDataValue:\x02\x38\x01"s\n\nQueryValue\x12\x14\n\ntext_value\x18\x01'
    b" \x01(\tH\x00\x12\x16\n\x0cnumber_value\x18\x02"
    b" \x01(\x12H\x00\x12\x17\n\rboolean_value\x18\x03"
    b" \x01(\x08H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04"
    b' \x01(\x01H\x00\x42\x06\n\x04\x64\x61ta"4\n\x12PayloadDescription\x12\x0c\n\x04type\x18\x01'
    b" \x01(\t\x12\x10\n\x08revision\x18\x02"
    b' \x01(\t2\xdf\t\n\nEventStore\x12h\n\x0b\x41ppendEvent\x12&.io.axoniq.axonserver.grpc.event.Event\x1a-.io.axoniq.axonserver.grpc.event.Confirmation"\x00(\x01\x12i\n\x0e\x41ppendSnapshot\x12&.io.axoniq.axonserver.grpc.event.Event\x1a-.io.axoniq.axonserver.grpc.event.Confirmation"\x00\x12}\n\x13ListAggregateEvents\x12:.io.axoniq.axonserver.grpc.event.GetAggregateEventsRequest\x1a&.io.axoniq.axonserver.grpc.event.Event"\x00\x30\x01\x12\x83\x01\n\x16ListAggregateSnapshots\x12=.io.axoniq.axonserver.grpc.event.GetAggregateSnapshotsRequest\x1a&.io.axoniq.axonserver.grpc.event.Event"\x00\x30\x01\x12v\n\nListEvents\x12\x31.io.axoniq.axonserver.grpc.event.GetEventsRequest\x1a/.io.axoniq.axonserver.grpc.event.EventWithToken"\x00(\x01\x30\x01\x12\x98\x01\n\x15ReadHighestSequenceNr\x12=.io.axoniq.axonserver.grpc.event.ReadHighestSequenceNrRequest\x1a>.io.axoniq.axonserver.grpc.event.ReadHighestSequenceNrResponse"\x00\x12~\n\x0bQueryEvents\x12\x33.io.axoniq.axonserver.grpc.event.QueryEventsRequest\x1a\x34.io.axoniq.axonserver.grpc.event.QueryEventsResponse"\x00(\x01\x30\x01\x12x\n\rGetFirstToken\x12\x35.io.axoniq.axonserver.grpc.event.GetFirstTokenRequest\x1a..io.axoniq.axonserver.grpc.event.TrackingToken"\x00\x12v\n\x0cGetLastToken\x12\x34.io.axoniq.axonserver.grpc.event.GetLastTokenRequest\x1a..io.axoniq.axonserver.grpc.event.TrackingToken"\x00\x12r\n\nGetTokenAt\x12\x32.io.axoniq.axonserver.grpc.event.GetTokenAtRequest\x1a..io.axoniq.axonserver.grpc.event.TrackingToken"\x00\x42\x02P\x01\x62\x06proto3'
)


_GETFIRSTTOKENREQUEST = DESCRIPTOR.message_types_by_name["GetFirstTokenRequest"]
_GETLASTTOKENREQUEST = DESCRIPTOR.message_types_by_name["GetLastTokenRequest"]
_GETTOKENATREQUEST = DESCRIPTOR.message_types_by_name["GetTokenAtRequest"]
_TRACKINGTOKEN = DESCRIPTOR.message_types_by_name["TrackingToken"]
_EVENTWITHTOKEN = DESCRIPTOR.message_types_by_name["EventWithToken"]
_QUERYEVENTSREQUEST = DESCRIPTOR.message_types_by_name["QueryEventsRequest"]
_QUERYEVENTSRESPONSE = DESCRIPTOR.message_types_by_name["QueryEventsResponse"]
_COLUMNSRESPONSE = DESCRIPTOR.message_types_by_name["ColumnsResponse"]
_ROWRESPONSE = DESCRIPTOR.message_types_by_name["RowResponse"]
_ROWRESPONSE_VALUESENTRY = _ROWRESPONSE.nested_types_by_name["ValuesEntry"]
_READHIGHESTSEQUENCENRREQUEST = DESCRIPTOR.message_types_by_name[
    "ReadHighestSequenceNrRequest"
]
_READHIGHESTSEQUENCENRRESPONSE = DESCRIPTOR.message_types_by_name[
    "ReadHighestSequenceNrResponse"
]
_CONFIRMATION = DESCRIPTOR.message_types_by_name["Confirmation"]
_GETAGGREGATEEVENTSREQUEST = DESCRIPTOR.message_types_by_name[
    "GetAggregateEventsRequest"
]
_GETAGGREGATESNAPSHOTSREQUEST = DESCRIPTOR.message_types_by_name[
    "GetAggregateSnapshotsRequest"
]
_GETEVENTSREQUEST = DESCRIPTOR.message_types_by_name["GetEventsRequest"]
_EVENT = DESCRIPTOR.message_types_by_name["Event"]
_EVENT_METADATAENTRY = _EVENT.nested_types_by_name["MetaDataEntry"]
_QUERYVALUE = DESCRIPTOR.message_types_by_name["QueryValue"]
_PAYLOADDESCRIPTION = DESCRIPTOR.message_types_by_name["PayloadDescription"]
GetFirstTokenRequest = _reflection.GeneratedProtocolMessageType(
    "GetFirstTokenRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETFIRSTTOKENREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.GetFirstTokenRequest)
    },
)
_sym_db.RegisterMessage(GetFirstTokenRequest)

GetLastTokenRequest = _reflection.GeneratedProtocolMessageType(
    "GetLastTokenRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETLASTTOKENREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.GetLastTokenRequest)
    },
)
_sym_db.RegisterMessage(GetLastTokenRequest)

GetTokenAtRequest = _reflection.GeneratedProtocolMessageType(
    "GetTokenAtRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETTOKENATREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.GetTokenAtRequest)
    },
)
_sym_db.RegisterMessage(GetTokenAtRequest)

TrackingToken = _reflection.GeneratedProtocolMessageType(
    "TrackingToken",
    (_message.Message,),
    {
        "DESCRIPTOR": _TRACKINGTOKEN,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.TrackingToken)
    },
)
_sym_db.RegisterMessage(TrackingToken)

EventWithToken = _reflection.GeneratedProtocolMessageType(
    "EventWithToken",
    (_message.Message,),
    {
        "DESCRIPTOR": _EVENTWITHTOKEN,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.EventWithToken)
    },
)
_sym_db.RegisterMessage(EventWithToken)

QueryEventsRequest = _reflection.GeneratedProtocolMessageType(
    "QueryEventsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUERYEVENTSREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.QueryEventsRequest)
    },
)
_sym_db.RegisterMessage(QueryEventsRequest)

QueryEventsResponse = _reflection.GeneratedProtocolMessageType(
    "QueryEventsResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUERYEVENTSRESPONSE,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.QueryEventsResponse)
    },
)
_sym_db.RegisterMessage(QueryEventsResponse)

ColumnsResponse = _reflection.GeneratedProtocolMessageType(
    "ColumnsResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _COLUMNSRESPONSE,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.ColumnsResponse)
    },
)
_sym_db.RegisterMessage(ColumnsResponse)

RowResponse = _reflection.GeneratedProtocolMessageType(
    "RowResponse",
    (_message.Message,),
    {
        "ValuesEntry": _reflection.GeneratedProtocolMessageType(
            "ValuesEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _ROWRESPONSE_VALUESENTRY,
                "__module__": "axonclient.protos.event_pb2"
                # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.RowResponse.ValuesEntry)
            },
        ),
        "DESCRIPTOR": _ROWRESPONSE,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.RowResponse)
    },
)
_sym_db.RegisterMessage(RowResponse)
_sym_db.RegisterMessage(RowResponse.ValuesEntry)

ReadHighestSequenceNrRequest = _reflection.GeneratedProtocolMessageType(
    "ReadHighestSequenceNrRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _READHIGHESTSEQUENCENRREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.ReadHighestSequenceNrRequest)
    },
)
_sym_db.RegisterMessage(ReadHighestSequenceNrRequest)

ReadHighestSequenceNrResponse = _reflection.GeneratedProtocolMessageType(
    "ReadHighestSequenceNrResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _READHIGHESTSEQUENCENRRESPONSE,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.ReadHighestSequenceNrResponse)
    },
)
_sym_db.RegisterMessage(ReadHighestSequenceNrResponse)

Confirmation = _reflection.GeneratedProtocolMessageType(
    "Confirmation",
    (_message.Message,),
    {
        "DESCRIPTOR": _CONFIRMATION,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.Confirmation)
    },
)
_sym_db.RegisterMessage(Confirmation)

GetAggregateEventsRequest = _reflection.GeneratedProtocolMessageType(
    "GetAggregateEventsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETAGGREGATEEVENTSREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.GetAggregateEventsRequest)
    },
)
_sym_db.RegisterMessage(GetAggregateEventsRequest)

GetAggregateSnapshotsRequest = _reflection.GeneratedProtocolMessageType(
    "GetAggregateSnapshotsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETAGGREGATESNAPSHOTSREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.GetAggregateSnapshotsRequest)
    },
)
_sym_db.RegisterMessage(GetAggregateSnapshotsRequest)

GetEventsRequest = _reflection.GeneratedProtocolMessageType(
    "GetEventsRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _GETEVENTSREQUEST,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.GetEventsRequest)
    },
)
_sym_db.RegisterMessage(GetEventsRequest)

Event = _reflection.GeneratedProtocolMessageType(
    "Event",
    (_message.Message,),
    {
        "MetaDataEntry": _reflection.GeneratedProtocolMessageType(
            "MetaDataEntry",
            (_message.Message,),
            {
                "DESCRIPTOR": _EVENT_METADATAENTRY,
                "__module__": "axonclient.protos.event_pb2"
                # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.Event.MetaDataEntry)
            },
        ),
        "DESCRIPTOR": _EVENT,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.Event)
    },
)
_sym_db.RegisterMessage(Event)
_sym_db.RegisterMessage(Event.MetaDataEntry)

QueryValue = _reflection.GeneratedProtocolMessageType(
    "QueryValue",
    (_message.Message,),
    {
        "DESCRIPTOR": _QUERYVALUE,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.QueryValue)
    },
)
_sym_db.RegisterMessage(QueryValue)

PayloadDescription = _reflection.GeneratedProtocolMessageType(
    "PayloadDescription",
    (_message.Message,),
    {
        "DESCRIPTOR": _PAYLOADDESCRIPTION,
        "__module__": "axonclient.protos.event_pb2"
        # @@protoc_insertion_point(class_scope:io.axoniq.axonserver.grpc.event.PayloadDescription)
    },
)
_sym_db.RegisterMessage(PayloadDescription)

_EVENTSTORE = DESCRIPTOR.services_by_name["EventStore"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"P\001"
    _ROWRESPONSE_VALUESENTRY._options = None
    _ROWRESPONSE_VALUESENTRY._serialized_options = b"8\001"
    _EVENT_METADATAENTRY._options = None
    _EVENT_METADATAENTRY._serialized_options = b"8\001"
    _GETFIRSTTOKENREQUEST._serialized_start = 98
    _GETFIRSTTOKENREQUEST._serialized_end = 120
    _GETLASTTOKENREQUEST._serialized_start = 122
    _GETLASTTOKENREQUEST._serialized_end = 143
    _GETTOKENATREQUEST._serialized_start = 145
    _GETTOKENATREQUEST._serialized_end = 181
    _TRACKINGTOKEN._serialized_start = 183
    _TRACKINGTOKEN._serialized_end = 213
    _EVENTWITHTOKEN._serialized_start = 215
    _EVENTWITHTOKEN._serialized_end = 301
    _QUERYEVENTSREQUEST._serialized_start = 303
    _QUERYEVENTSREQUEST._serialized_end = 386
    _QUERYEVENTSRESPONSE._serialized_start = 389
    _QUERYEVENTSRESPONSE._serialized_end = 622
    _COLUMNSRESPONSE._serialized_start = 624
    _COLUMNSRESPONSE._serialized_end = 657
    _ROWRESPONSE._serialized_start = 660
    _ROWRESPONSE._serialized_end = 969
    _ROWRESPONSE_VALUESENTRY._serialized_start = 879
    _ROWRESPONSE_VALUESENTRY._serialized_end = 969
    _READHIGHESTSEQUENCENRREQUEST._serialized_start = 971
    _READHIGHESTSEQUENCENRREQUEST._serialized_end = 1049
    _READHIGHESTSEQUENCENRRESPONSE._serialized_start = 1051
    _READHIGHESTSEQUENCENRRESPONSE._serialized_end = 1106
    _CONFIRMATION._serialized_start = 1108
    _CONFIRMATION._serialized_end = 1139
    _GETAGGREGATEEVENTSREQUEST._serialized_start = 1141
    _GETAGGREGATEEVENTSREQUEST._serialized_end = 1241
    _GETAGGREGATESNAPSHOTSREQUEST._serialized_start = 1243
    _GETAGGREGATESNAPSHOTSREQUEST._serialized_end = 1364
    _GETEVENTSREQUEST._serialized_start = 1367
    _GETEVENTSREQUEST._serialized_end = 1570
    _EVENT._serialized_start = 1573
    _EVENT._serialized_end = 1960
    _EVENT_METADATAENTRY._serialized_start = 1871
    _EVENT_METADATAENTRY._serialized_end = 1960
    _QUERYVALUE._serialized_start = 1962
    _QUERYVALUE._serialized_end = 2077
    _PAYLOADDESCRIPTION._serialized_start = 2079
    _PAYLOADDESCRIPTION._serialized_end = 2131
    _EVENTSTORE._serialized_start = 2134
    _EVENTSTORE._serialized_end = 3381
# @@protoc_insertion_point(module_scope)
