"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import axonclient.protos.common_pb2
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class QueryProviderOutbound(google.protobuf.message.Message):
    """Message containing Query related instructions for Axon Server"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIBE_FIELD_NUMBER: builtins.int
    UNSUBSCRIBE_FIELD_NUMBER: builtins.int
    FLOW_CONTROL_FIELD_NUMBER: builtins.int
    QUERY_RESPONSE_FIELD_NUMBER: builtins.int
    QUERY_COMPLETE_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_QUERY_RESPONSE_FIELD_NUMBER: builtins.int
    ACK_FIELD_NUMBER: builtins.int
    INSTRUCTION_ID_FIELD_NUMBER: builtins.int
    instruction_id: builtins.str
    """Instruction identifier. If this identifier is set, this instruction will be acknowledged via inbound stream"""
    @property
    def subscribe(self) -> Global___QuerySubscription:
        """Registers a Query Handler with AxonServer"""

    @property
    def unsubscribe(self) -> Global___QuerySubscription:
        """Unregisters a Query Handler with AxonServer"""

    @property
    def flow_control(self) -> axonclient.protos.common_pb2.FlowControl:
        """Grant permits to AxonServer to send a number of messages to the client"""

    @property
    def query_response(self) -> Global___QueryResponse:
        """Sends a Response to a Query received via the inbound stream"""

    @property
    def query_complete(self) -> Global___QueryComplete:
        """Indicator that all responses for Query have been sent"""

    @property
    def subscription_query_response(self) -> Global___SubscriptionQueryResponse:
        """Sends a response for a Subscription Query that has been received via the inbound stream"""

    @property
    def ack(self) -> axonclient.protos.common_pb2.InstructionAck:
        """Acknowledgement of previously sent instruction via inbound stream"""

    def __init__(
        self,
        *,
        subscribe: Global___QuerySubscription | None = ...,
        unsubscribe: Global___QuerySubscription | None = ...,
        flow_control: axonclient.protos.common_pb2.FlowControl | None = ...,
        query_response: Global___QueryResponse | None = ...,
        query_complete: Global___QueryComplete | None = ...,
        subscription_query_response: Global___SubscriptionQueryResponse | None = ...,
        ack: axonclient.protos.common_pb2.InstructionAck | None = ...,
        instruction_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "flow_control",
            b"flow_control",
            "query_complete",
            b"query_complete",
            "query_response",
            b"query_response",
            "request",
            b"request",
            "subscribe",
            b"subscribe",
            "subscription_query_response",
            b"subscription_query_response",
            "unsubscribe",
            b"unsubscribe",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "flow_control",
            b"flow_control",
            "instruction_id",
            b"instruction_id",
            "query_complete",
            b"query_complete",
            "query_response",
            b"query_response",
            "request",
            b"request",
            "subscribe",
            b"subscribe",
            "subscription_query_response",
            b"subscription_query_response",
            "unsubscribe",
            b"unsubscribe",
        ],
    ) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["request", b"request"]) -> (
        typing.Literal[
            "subscribe",
            "unsubscribe",
            "flow_control",
            "query_response",
            "query_complete",
            "subscription_query_response",
            "ack",
        ]
        | None
    ): ...

Global___QueryProviderOutbound: typing_extensions.TypeAlias = QueryProviderOutbound

@typing.final
class QueryProviderInbound(google.protobuf.message.Message):
    """Queries or Query related instructions from AxonServer for the connected application"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ACK_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_QUERY_REQUEST_FIELD_NUMBER: builtins.int
    INSTRUCTION_ID_FIELD_NUMBER: builtins.int
    instruction_id: builtins.str
    """Instruction identifier. If this identifier is set, this instruction will be acknowledged via outbound stream"""
    @property
    def ack(self) -> axonclient.protos.common_pb2.InstructionAck:
        """Acknowledgement of previously sent instruction via outbound stream"""

    @property
    def query(self) -> Global___QueryRequest:
        """Represents an incoming Query, for which this component is expected to provide a response"""

    @property
    def subscription_query_request(self) -> Global___SubscriptionQueryRequest:
        """Represents an incoming Subscription Query, for which this component is expected to provide a response and updates"""

    def __init__(
        self,
        *,
        ack: axonclient.protos.common_pb2.InstructionAck | None = ...,
        query: Global___QueryRequest | None = ...,
        subscription_query_request: Global___SubscriptionQueryRequest | None = ...,
        instruction_id: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "query",
            b"query",
            "request",
            b"request",
            "subscription_query_request",
            b"subscription_query_request",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "ack",
            b"ack",
            "instruction_id",
            b"instruction_id",
            "query",
            b"query",
            "request",
            b"request",
            "subscription_query_request",
            b"subscription_query_request",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["request", b"request"]
    ) -> typing.Literal["ack", "query", "subscription_query_request"] | None: ...

Global___QueryProviderInbound: typing_extensions.TypeAlias = QueryProviderInbound

@typing.final
class QueryComplete(google.protobuf.message.Message):
    """Message indicating that all available responses to an incoming Query have been provided."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    REQUEST_ID_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    """A unique identifier for this message"""
    request_id: builtins.str
    """The identifier of the incoming query to complete"""
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        request_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "message_id", b"message_id", "request_id", b"request_id"
        ],
    ) -> None: ...

Global___QueryComplete: typing_extensions.TypeAlias = QueryComplete

@typing.final
class QueryRequest(google.protobuf.message.Message):
    """Message representing an incoming Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> axonclient.protos.common_pb2.MetaDataValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: axonclient.protos.common_pb2.MetaDataValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    META_DATA_FIELD_NUMBER: builtins.int
    RESPONSE_TYPE_FIELD_NUMBER: builtins.int
    PROCESSING_INSTRUCTIONS_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The message ID of the incoming Query"""
    query: builtins.str
    """The name of the Query to execute"""
    timestamp: builtins.int
    """The timestamp of the Query creation"""
    client_id: builtins.str
    """The unique identifier of the client instance dispatching the query"""
    component_name: builtins.str
    """The Name of the Component dispatching the query"""
    @property
    def payload(self) -> axonclient.protos.common_pb2.SerializedObject:
        """A payload accompanying the Query"""

    @property
    def meta_data(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, axonclient.protos.common_pb2.MetaDataValue
    ]:
        """Meta Data providing contextual information of the Query"""

    @property
    def response_type(self) -> axonclient.protos.common_pb2.SerializedObject:
        """An object describing the expectations of the Response Type"""

    @property
    def processing_instructions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        axonclient.protos.common_pb2.ProcessingInstruction
    ]:
        """Any instructions for components Routing or Handling the Query"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        query: builtins.str = ...,
        timestamp: builtins.int = ...,
        payload: axonclient.protos.common_pb2.SerializedObject | None = ...,
        meta_data: (
            collections.abc.Mapping[
                builtins.str, axonclient.protos.common_pb2.MetaDataValue
            ]
            | None
        ) = ...,
        response_type: axonclient.protos.common_pb2.SerializedObject | None = ...,
        processing_instructions: (
            collections.abc.Iterable[axonclient.protos.common_pb2.ProcessingInstruction]
            | None
        ) = ...,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "payload", b"payload", "response_type", b"response_type"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "message_identifier",
            b"message_identifier",
            "meta_data",
            b"meta_data",
            "payload",
            b"payload",
            "processing_instructions",
            b"processing_instructions",
            "query",
            b"query",
            "response_type",
            b"response_type",
            "timestamp",
            b"timestamp",
        ],
    ) -> None: ...

Global___QueryRequest: typing_extensions.TypeAlias = QueryRequest

@typing.final
class QueryResponse(google.protobuf.message.Message):
    """Message that represents the Response to a Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> axonclient.protos.common_pb2.MetaDataValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: axonclient.protos.common_pb2.MetaDataValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    META_DATA_FIELD_NUMBER: builtins.int
    PROCESSING_INSTRUCTIONS_FIELD_NUMBER: builtins.int
    REQUEST_IDENTIFIER_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The unique identifier of the Response Message"""
    error_code: builtins.str
    """An Error Code identifying the type of error, if any"""
    request_identifier: builtins.str
    """The unique identifier of the Query to which this is a response"""
    @property
    def error_message(self) -> axonclient.protos.common_pb2.ErrorMessage:
        """A detailed description of the error, if any"""

    @property
    def payload(self) -> axonclient.protos.common_pb2.SerializedObject:
        """The Payload of the Response Message"""

    @property
    def meta_data(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, axonclient.protos.common_pb2.MetaDataValue
    ]:
        """Any Meta Data describing the context of the Response Message"""

    @property
    def processing_instructions(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        axonclient.protos.common_pb2.ProcessingInstruction
    ]:
        """Any instructions for components Routing or Handling the Response Message"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        error_code: builtins.str = ...,
        error_message: axonclient.protos.common_pb2.ErrorMessage | None = ...,
        payload: axonclient.protos.common_pb2.SerializedObject | None = ...,
        meta_data: (
            collections.abc.Mapping[
                builtins.str, axonclient.protos.common_pb2.MetaDataValue
            ]
            | None
        ) = ...,
        processing_instructions: (
            collections.abc.Iterable[axonclient.protos.common_pb2.ProcessingInstruction]
            | None
        ) = ...,
        request_identifier: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "error_message", b"error_message", "payload", b"payload"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "error_code",
            b"error_code",
            "error_message",
            b"error_message",
            "message_identifier",
            b"message_identifier",
            "meta_data",
            b"meta_data",
            "payload",
            b"payload",
            "processing_instructions",
            b"processing_instructions",
            "request_identifier",
            b"request_identifier",
        ],
    ) -> None: ...

Global___QueryResponse: typing_extensions.TypeAlias = QueryResponse

@typing.final
class SubscriptionQuery(google.protobuf.message.Message):
    """Message that represents a Subscription Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIPTION_IDENTIFIER_FIELD_NUMBER: builtins.int
    NUMBER_OF_PERMITS_FIELD_NUMBER: builtins.int
    QUERY_REQUEST_FIELD_NUMBER: builtins.int
    UPDATE_RESPONSE_TYPE_FIELD_NUMBER: builtins.int
    subscription_identifier: builtins.str
    """A unique identifier for this subscription"""
    number_of_permits: builtins.int
    """The number of messages the Server may send before needing to await additional permits"""
    @property
    def query_request(self) -> Global___QueryRequest:
        """The Query describing the desire for information"""

    @property
    def update_response_type(self) -> axonclient.protos.common_pb2.SerializedObject:
        """A description of the type of Object expected as Update Responses"""

    def __init__(
        self,
        *,
        subscription_identifier: builtins.str = ...,
        number_of_permits: builtins.int = ...,
        query_request: Global___QueryRequest | None = ...,
        update_response_type: (
            axonclient.protos.common_pb2.SerializedObject | None
        ) = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "query_request",
            b"query_request",
            "update_response_type",
            b"update_response_type",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "number_of_permits",
            b"number_of_permits",
            "query_request",
            b"query_request",
            "subscription_identifier",
            b"subscription_identifier",
            "update_response_type",
            b"update_response_type",
        ],
    ) -> None: ...

Global___SubscriptionQuery: typing_extensions.TypeAlias = SubscriptionQuery

@typing.final
class QueryUpdate(google.protobuf.message.Message):
    """A message containing an Update of a Query Subscription Response"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class MetaDataEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> axonclient.protos.common_pb2.MetaDataValue: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: axonclient.protos.common_pb2.MetaDataValue | None = ...,
        ) -> None: ...
        def HasField(
            self, field_name: typing.Literal["value", b"value"]
        ) -> builtins.bool: ...
        def ClearField(
            self, field_name: typing.Literal["key", b"key", "value", b"value"]
        ) -> None: ...

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    PAYLOAD_FIELD_NUMBER: builtins.int
    META_DATA_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The unique identifier of this Update"""
    client_id: builtins.str
    """The identifier of the Client instance providing the Update"""
    component_name: builtins.str
    """The Component Name of the Client providing the Update"""
    @property
    def payload(self) -> axonclient.protos.common_pb2.SerializedObject:
        """The object representing the Update"""

    @property
    def meta_data(
        self,
    ) -> google.protobuf.internal.containers.MessageMap[
        builtins.str, axonclient.protos.common_pb2.MetaDataValue
    ]:
        """Meta Data providing contextual information of the Update"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        payload: axonclient.protos.common_pb2.SerializedObject | None = ...,
        meta_data: (
            collections.abc.Mapping[
                builtins.str, axonclient.protos.common_pb2.MetaDataValue
            ]
            | None
        ) = ...,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["payload", b"payload"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "message_identifier",
            b"message_identifier",
            "meta_data",
            b"meta_data",
            "payload",
            b"payload",
        ],
    ) -> None: ...

Global___QueryUpdate: typing_extensions.TypeAlias = QueryUpdate

@typing.final
class QueryUpdateComplete(google.protobuf.message.Message):
    """Message indicating that all relevant Updates have been sent for a Subscription Query, and that no further Updates are available"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    client_id: builtins.str
    """The identifier of the Client instance providing the Update"""
    component_name: builtins.str
    """The Component Name of the Client providing the Update"""
    def __init__(
        self,
        *,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id", b"client_id", "component_name", b"component_name"
        ],
    ) -> None: ...

Global___QueryUpdateComplete: typing_extensions.TypeAlias = QueryUpdateComplete

@typing.final
class QueryUpdateCompleteExceptionally(google.protobuf.message.Message):
    """Message indicating that an Error occurred and that no Updates will be sent for a Subscription Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CLIENT_ID_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    ERROR_CODE_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    client_id: builtins.str
    """The identifier of the Client instance providing the Update"""
    component_name: builtins.str
    """The Component Name of the Client providing the Update"""
    error_code: builtins.str
    """The Code describing the type of Error that occurred"""
    @property
    def error_message(self) -> axonclient.protos.common_pb2.ErrorMessage:
        """A detailed description of the error, if available"""

    def __init__(
        self,
        *,
        client_id: builtins.str = ...,
        component_name: builtins.str = ...,
        error_code: builtins.str = ...,
        error_message: axonclient.protos.common_pb2.ErrorMessage | None = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing.Literal["error_message", b"error_message"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "error_code",
            b"error_code",
            "error_message",
            b"error_message",
        ],
    ) -> None: ...

Global___QueryUpdateCompleteExceptionally: typing_extensions.TypeAlias = (
    QueryUpdateCompleteExceptionally
)

@typing.final
class SubscriptionQueryRequest(google.protobuf.message.Message):
    """Message describing possible interactions for a Subscription Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUBSCRIBE_FIELD_NUMBER: builtins.int
    UNSUBSCRIBE_FIELD_NUMBER: builtins.int
    GET_INITIAL_RESULT_FIELD_NUMBER: builtins.int
    FLOW_CONTROL_FIELD_NUMBER: builtins.int
    @property
    def subscribe(self) -> Global___SubscriptionQuery:
        """Start a Subscription Query with the given details."""

    @property
    def unsubscribe(self) -> Global___SubscriptionQuery:
        """Ends a previously started Subscription Query with the given details"""

    @property
    def get_initial_result(self) -> Global___SubscriptionQuery:
        """Requests the initial result of a subscription query to be sent. This should always be done after opening the
        subscription query itself, to remove concurrency conflicts with Update messages.
        """

    @property
    def flow_control(self) -> Global___SubscriptionQuery:
        """Allows the Server to provide additional Updates to be sent. Only the `number_of_permits` field needs to be
        set on this message.
        """

    def __init__(
        self,
        *,
        subscribe: Global___SubscriptionQuery | None = ...,
        unsubscribe: Global___SubscriptionQuery | None = ...,
        get_initial_result: Global___SubscriptionQuery | None = ...,
        flow_control: Global___SubscriptionQuery | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "flow_control",
            b"flow_control",
            "get_initial_result",
            b"get_initial_result",
            "request",
            b"request",
            "subscribe",
            b"subscribe",
            "unsubscribe",
            b"unsubscribe",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "flow_control",
            b"flow_control",
            "get_initial_result",
            b"get_initial_result",
            "request",
            b"request",
            "subscribe",
            b"subscribe",
            "unsubscribe",
            b"unsubscribe",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["request", b"request"]
    ) -> (
        typing.Literal["subscribe", "unsubscribe", "get_initial_result", "flow_control"]
        | None
    ): ...

Global___SubscriptionQueryRequest: typing_extensions.TypeAlias = (
    SubscriptionQueryRequest
)

@typing.final
class SubscriptionQueryResponse(google.protobuf.message.Message):
    """Represents a Response Message for a Subscription Query"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_IDENTIFIER_FIELD_NUMBER: builtins.int
    SUBSCRIPTION_IDENTIFIER_FIELD_NUMBER: builtins.int
    INITIAL_RESULT_FIELD_NUMBER: builtins.int
    UPDATE_FIELD_NUMBER: builtins.int
    COMPLETE_FIELD_NUMBER: builtins.int
    COMPLETE_EXCEPTIONALLY_FIELD_NUMBER: builtins.int
    message_identifier: builtins.str
    """The unique identifier for this message"""
    subscription_identifier: builtins.str
    """The identifier of the subscription query this is a response for"""
    @property
    def initial_result(self) -> Global___QueryResponse:
        """Provides an Initial Response"""

    @property
    def update(self) -> Global___QueryUpdate:
        """Provides an Update Response"""

    @property
    def complete(self) -> Global___QueryUpdateComplete:
        """Indicates the Query is complete, and no more Updates will be sent"""

    @property
    def complete_exceptionally(self) -> Global___QueryUpdateCompleteExceptionally:
        """Indicates the Query failed exceptionally, and no more Updates will be sent"""

    def __init__(
        self,
        *,
        message_identifier: builtins.str = ...,
        subscription_identifier: builtins.str = ...,
        initial_result: Global___QueryResponse | None = ...,
        update: Global___QueryUpdate | None = ...,
        complete: Global___QueryUpdateComplete | None = ...,
        complete_exceptionally: Global___QueryUpdateCompleteExceptionally | None = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing.Literal[
            "complete",
            b"complete",
            "complete_exceptionally",
            b"complete_exceptionally",
            "initial_result",
            b"initial_result",
            "response",
            b"response",
            "update",
            b"update",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "complete",
            b"complete",
            "complete_exceptionally",
            b"complete_exceptionally",
            "initial_result",
            b"initial_result",
            "message_identifier",
            b"message_identifier",
            "response",
            b"response",
            "subscription_identifier",
            b"subscription_identifier",
            "update",
            b"update",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing.Literal["response", b"response"]
    ) -> (
        typing.Literal["initial_result", "update", "complete", "complete_exceptionally"]
        | None
    ): ...

Global___SubscriptionQueryResponse: typing_extensions.TypeAlias = (
    SubscriptionQueryResponse
)

@typing.final
class QuerySubscription(google.protobuf.message.Message):
    """Message containing details of a Registration of a Query Handler in a component"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MESSAGE_ID_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    RESULT_NAME_FIELD_NUMBER: builtins.int
    COMPONENT_NAME_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    NR_OF_HANDLERS_FIELD_NUMBER: builtins.int
    message_id: builtins.str
    """The unique identifier of this Message"""
    query: builtins.str
    """The name of the Query the Handler is subscribed to"""
    result_name: builtins.str
    """The type of Result this Handler produces"""
    component_name: builtins.str
    """The name of the Component containing the Query Handler"""
    client_id: builtins.str
    """The unique identifier of the Client Instance containing the Query Handler"""
    nr_of_handlers: builtins.int
    """The number of Query Handlers registered within this Component with the same details. This number is used to
    calculate the number of candidates for Scatter-Gather Queries.
    """
    def __init__(
        self,
        *,
        message_id: builtins.str = ...,
        query: builtins.str = ...,
        result_name: builtins.str = ...,
        component_name: builtins.str = ...,
        client_id: builtins.str = ...,
        nr_of_handlers: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "client_id",
            b"client_id",
            "component_name",
            b"component_name",
            "message_id",
            b"message_id",
            "nr_of_handlers",
            b"nr_of_handlers",
            "query",
            b"query",
            "result_name",
            b"result_name",
        ],
    ) -> None: ...

Global___QuerySubscription: typing_extensions.TypeAlias = QuerySubscription
